---
- name: Provision server
  hosts: all
  remote_user: ec2-user
  gather_facts: no
  vars:
    ansible_ssh_pipelining: no
    env: "dev"
    azone: "az1"
    sub_zone: "app"
    sg_zone: "appserver"
    env_az: "{{ env }}-{{ azone }}"
    splunk_target_layer: "app"
  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/env/{{ env }}/vault.yml"
    - "./../../vars/env/{{ env }}/env.yml"
    - "./../../vars/all_var.yml"

  roles:
    - ../../roles/aws
    - ../../roles/app_user
    - ../../roles/app_prep
    - ../../roles/app_logs
    - ../../roles/app_install
    - ../../roles/env_config
    - ../../roles/nginx
    - ../../roles/semanage_apps
    - ../../roles/semanage_virtualenv
