---
# File: playbook/dataserver/roles/postgres/tasks/restore_setup.yml
# Created: 6/22/17
# Author: '@ekivemark'
# Copy bash scripts and support files to dataserver to enable restore

- name: "Create Restore location /data/pgbackup/restore"
  become_user: root
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ db_server_account }}"
    group: "{{ db_server_account }}"
  with_items:
  - "/data/pgbackup/restore"

- name: "Install private key to decrypt compressed backup files"
  become_user: root
  become: yes
  copy:
    owner: "{{ db_server_account }}"
    group: "{{ db_server_account }}"
    mode: "0600"
    content: "{{ vault_env_db_backup_private_key_current }}"
    dest: "/data/pgbackup/restore/backup_key.pem.private"

- name: "Create a Database re-initialization script"
  become_user: root
  become: yes
  copy:
    src: "../templates/db_init_script.j2"
    dest: "/data/pgbackup/restore/re_init_script.sql"
    owner: "{{ db_server_account }}"
    group: "{{ db_server_account }}"
    mode: "0660"

- name: "install unpack script"
  become_user: root
  become: yes
  copy:
    src: "../templates/{{ item }}.j2"
    dest: "/data/pgbackup/restore/{{ item }}"
    owner: "{{ db_server_account }}"
    group: "{{ db_server_account }}"
    mode: "0770"
  with_items:
  - "unpack.sh"
  - "readme.sh"



