---
# File: playbook/platform/roles/etc_hosts/tasks/main.yml
# Created: 7/31/17
# Author: '@ekivemark'


- name: "debugging"
  debug:
    msg: "working with servers: {% for host in build_target %}{{ host }}{% endfor %}"

- name: Generate /etc/hosts file
  become: yes
  become_user: root
  template:
    src: "../templates/hosts.j2"
    dest: "/etc/hosts.ansible"

