---
# File: playbook/platform/roles/etc_hosts/tasks/main.yml
# Created: 7/31/17
# Author: '@ekivemark'


- name: Generate /etc/hosts file
  become: yes
  become_user: root
  template:
    src: "../templates/hosts.j2"
    dest: "/etc/hosts.ansible"

- name: "copy /etc/hosts.ansible to remotes"
  become: yes
  become_user: root
  copy:
    src: "/etc/hosts.ansible"
    dest: "/etc/hosts."
    owner: root
    group: root
    mode: 0644

- name: "update mgmtserver hosts file"
  connection: local
  become_user: root
  become: yes
  copy:
    src: "/etc/hosts.ansible"
    dest: "/etc/hosts."
    owner: root
    group: root
    mode: 0644



