# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "bb-terraform-state"
    dynamodb_table = "bb-terraform-state"
    encrypt        = true
    key            = "workspaces/cwl_subscrip_filter/terraform.tfstate"
    region         = "us-east-1"
  }
}
