---
- hosts: appleaderservers appfollowerservers
  vars_files:
    - ../../vars/playbook/vars.yml
  remote_user: "{{ remote_user_account }}"
  become: yes
  become_user: root
  
  tasks:
  - name: become root and activate virtualenv
    become: yes
    become_method: sudo
    become_user: root
    action: shell source /var/virtualenv/hhs_o_server/bin/activate

  - name: switch to app folder
    action: "shell cd {{ install_root }}/{{ project_name }}/"

  - git:
      repo: "{{ project_repo }}"
      dest: "{{ install_root }}/{{ project_name }}"
      force: yes
      version: develop

  # change ownership of files
  - file:
      path: "{{ install_root }}/{{ project_name }}/"
      recurse: yes
      owner: pyapps
      group: apache

  # make manage.py executable
  - file:
      path: "{{ install_root }}/{{ project_name }}/manage.py"
      state: touch
      mode: "u+rwx,g+rwx,o-rwx"

  # - name: Django collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ install_root }}/{{ project_name }}/"
    virtualenv: "{{ venv }}"

  # - name: Django migrate
  django_manage:
    command: migrate
    app_path: "{{ install_root }}/{{ project_name }}/"
    virtualenv: "{{ venv }}"

  - name: make sure apache server is running
    service: name=httpd state=started enabled=yes
 
  - name: Restart Apache
    action: shell /bin/echo $HOSTNAME
    notify: 
      - restart apache
 
  handlers: 
    - name: restart apache
      service: name=httpd state=restarted  

# vim:ft=ansible
