---
# a unix path-friendly name (IE, no spaces or special characters)
project_name: hhs_oauth_server

# git branch to deploy
git_branch: develop

# the base path to install to. You should not need to change this.
install_root: /var/pyapps/hhs_o_server

# the git repository URL for the project
# project_repo: git@github.com:transparenthealth/hhs_oauth_server.git
project_repo: https://github.com/transparenthealth/hhs_oauth_server.git

# The value of your django project's STATIC_ROOT settings.
# This will be the directory that django's `collectstatic` management command
# copies static files to, and it must be an absolute path. The default value 
# here assumes that STATIC_ROOT is set in your settings.py like so:
# STATIC_ROOT = os.path.abspath(os.path.join(BASE_DIR, 'static'))
static_root: "{{ install_root }}/{{ project_name }}/static"


