---
# File: main.yml 
# Created: 6/7/17
# Author: '@ekivemark'
# Replace postgresql.conf with needed settings
# Using template rather than editing default file
# Version 1.0

- name: "write postgresql.conf template"
  template:
    src: "../templates/postgresql.conf.j2"
    dest: "{{ db_server_data_dir }}/postgresql.conf"
    backup: yes
    owner: "{{ db_server_account }}"
    group: "{{ db_server_account }}"
    mode: "u+rwx"

- name: "Copy postgresql.auto.conf into place if not found"
  file:
    src: "/var/lib/pgsql/9.6/data/{{ item }}"
    dest: "{{ db_server_data_dir }}/{{ item }}"
    remote_src: yes
    force: no
    owner: "{{ db_server_account }}"
    group: "{{ db_server_account }}"
    mode: "u+rwx"
  with_items:
    - postgresql.auto.conf

