---
- name: "Set selinux status"
  become_user: "{{ remote_admin_account }}"
  become: yes
  selinux:
    policy: "{{ cf_app_selinux_policy }}"
    state: "{{ cf_app_selinux_state }}"
  register: check_selinux
# TEMP lines to help with debugging SELINUX setup. Cleanup later!
- debug: msg="{{ check_selinux.msg }}"
