---
# File: main.yml 
# Created: 6/18/17
# Author: '@ekivemark'

# Install certs created on mgmtserver

- name: "install certs on dataserver"
  copy:
    src: "/root/ca/{{ item }}"
    dest: "/data/pgsql/9.6/data/{{ item }}"
    owner: postgres
    group: postgres
    mode: "0600"
  with_items:
    - "{{ ca_key }}"
    - "{{ ca_cert }}"


- name: "re-write postgresql.conf"
  include: "./roles/update_postgres_conf/tasks/main.yml"

- name: "re-write pg_hba.conf"
  include: "./roles/update_pg_hba/tasks/main.yml"


#- name: "restart postgresql"
#  service :
#    name: postgresql-9.6
#    state: restarted

- name: "restart database on RHEL {{ rhel_version }}"
  become_user: "{{ db_server_account}}"
  become: yes
  shell: |
    export PGDATA={{db_server_data_dir }}
    cd $PGDATA
    /usr/pgsql-9.6/bin/pg_ctl -D {{ db_server_data_dir }} -l logfile restart
  when: rhel_version == "7"
  register: postgres_7_restart_result

- name: "restart Database"
  become_user: root
  become: yes
  service:
    name: postgresql-9.6
    state: started
  when: rhel_version == "6"
  register: postgres_restart_result


