---
# File: playbook/debug/check_all_splunk.yml
# Created: 5/17/17
# Author: '@ekivemark'

# Process splunk config for groups of servers

- name: "Check appservers for splunk config"
  hosts: appservers
  # hosts: local
  # connection: local
  remote_user: ec2-user
  become_user: root
  become: yes
  gather_facts: True
  vars:
    build_target: "appservers"
    ansible_ssh_pipelining: no
    env: "impl"
    azone: "az1"
    sub_zone: "app"
    sg_zone: "appserver"
    env_az: "{{ env }}-{{ azone }}"
    env_cf_app_version: "01"
    # splunk_target_layer: "WEB | APP | DATA | MGMT"
    splunk_target_layer: "{{ sub_zone|upper }}"
    #    migrate: "yes"
    #    collectstatic: "yes"

  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/env/{{ env }}/vault.yml"
    - "./../../vars/env/{{ env }}/env.yml"
    - "./../../vars/all_var.yml"

  tasks:
  - include: ./check_splunk_config.yml

- name: "Check mgmtservers for splunk config"
  hosts: mgmtservers
  vars:
    build_target: "mgmtservers"
    sub_zone: "mgmt"
  tasks:
   - include: ./check_splunk_config.yml

- name: "Check dataservers for splunk config"
  hosts: dataservers
  vars:
    build_target: "dbservers"
    sub_zone: "data"
  tasks:
  - include: ./check_splunk_config.yml

