---
# File: playbook/debug/check_splunk_config.yml
# Created: 5/17/17
# Author: '@ekivemark'

# Check the setting of the splunk config file

- hosts: "{{ build_target }}"
  # hosts: appservers
  # connection: local
  remote_user: ec2-user
  become_user: root
  become: yes
  gather_facts: True
  vars:
    ansible_ssh_pipelining: no
    env: "impl"
    azone: "az1"
    sub_zone: "app"
    sg_zone: "appserver"
    env_az: "{{ env }}-{{ azone }}"
    env_cf_app_version: "01"
    splunk_client_name: "BBAPI-{{ env|upper }}-{{ sub_zone|upper }}"
    #    migrate: "yes"
    #    collectstatic: "yes"
  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/env/{{ env }}/vault.yml"
    - "./../../vars/env/{{ env }}/env.yml"
    - "./../../vars/all_var.yml"

#  roles:
#    - ../../roles/splunk

  tasks:
  - include: ../../roles/splunk/tasks/main.yml

  - name: "Check Splunk Configuration..."
    become_user: root
    become: yes
    shell: " echo $HOSTNAME ; cat /opt/splunkforwarder/etc/system/local/deploymentclient.conf "
    register: splunk_config

  - name: "Here is the Splunk configuration for {{ hosts }}"
    debug:
      msg: "{{ splunk_config.stdout.split('\n') }}"
  - name: "Splunk Config Errors"
    debug:
      msg: "{{ splunk_config.stderr.split('\n') }}"

#  - hosts: dbservers
#    set_fact:
#      sub_zone: "data"
#      splunk_client_name: "BBAPI-{{ env|upper }}-{{ sub_zone|upper }}"
#
#  - name: "Check Splunk Configuration..."
#    become_user: root
#    become: yes
#
#    shell: " echo $HOSTNAME ; cat /opt/splunkforwarder/etc/system/local/deploymentclient.conf "
#    register: splunk_config_data
#
#  - name: "Here is the Splunk configuartion for {{ hosts }}"
#    debug:
#      msg: "{{ splunk_config_data.stdout.split('\n') }}"
#  - name: "Splunk Config Errors"
#    debug:
#      msg: "{{ splunk_config_data.stderr.split('\n') }}"
#
#  - hosts: appservers
#    set_fact:
#      sub_zone: "mgmt"
#      splunk_client_name: "BBAPI-{{ env|upper }}-{{ sub_zone|upper }}"
#
#  - name: "Check Splunk Configuration..."
#    become_user: root
#    become: yes
#
#    shell: " echo $HOSTNAME ; cat /opt/splunkforwarder/etc/system/local/deploymentclient.conf "
#    register: splunk_config_app
#
#  - name: "Here is the Splunk configuartion for {{ hosts }}"
#    debug:
#      msg: "{{ splunk_config_app.stdout.split('\n') }}"
#  - name: "Splunk Config Errors"
#    debug:
#      msg: "{{ splunk_config_app.stderr.split('\n') }}"
#
