---
# File: debug_print.yml 
# Created: 4/4/17


- hosts: all
  # Vars file is relative to playbook file

  tasks:
  - name: get variables
    include_vars:
      file: "../../vars/all_var.yml"

  - debug:
      msg: "Have we got variables: {{ venv }}"
#  - debug:
#      msg: "Project Dir: {{ common_project_dir }}"
#  - debug:
#      msg: "Vault remote user::{{ vault_env_remote_user_account }}"

  - name: Dump all vars
    template:
      src="../../templates/debug/dumpall.j2"
      dest="/tmp/ansible.all"
