---
# File: debug_print.yml 
# Created: 4/4/17


- hosts: all
  vars:
  env: "dev"
  # Vars file is relative to playbook file
  # Sequence: 1. Common variables
  # 2. encrypted vault file
  # 3. environment specific variables
  # 4. all_vars which reference the preceding three files.
  # common_ prefixes common variables
  # vault_env_ prefixes encrypted variables
  # env_ prefixes environment specific variables
  # all_var incorporates preceding variables and defines variables without prefixes.
  # use all_var variables in scripts.
  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/env/{{ env }}/vault.yml"
    - "./../../vars/env/{{ env }}/env.yml"
    - "./../../vars/all_var.yml"


  # Vars file is relative to playbook file

  tasks:
  - name: get variables
    include_vars:
      file: "../../vars/all_var.yml"

  - debug: msg="Have we got variables {{ venv }} / {{ common_project_dir }}"

  - shell: "/bin/echo hello world {{ item }}"

  - debug:
      var: common_project_dir
#  - debug: msg="Vault remote user- {{ vault_env_remote_user_account }}"

  - name: Dump all vars
    template:
      src="../../templates/debug/dumpall.j2"
      dest="/tmp/ansible.all"
