---
# File: playbook/debug/test_variables.yml
# Created: 4/5/17
# Ping all servers
# A basic script to check undefined variables.

- hosts: "{{ build_target }}"
  vars:
    env: "dev"
  # Vars file is relative to playbook file
  # Sequence: 1. Common variables
  # 2. encrypted vault file
  # 3. environment specific variables
  # 4. all_vars which reference the preceding three files.
  # common_ prefixes common variables
  # vault_env_ prefixes encrypted variables
  # env_ prefixes environment specific variables
  # all_var incorporates preceding variables and defines variables without prefixes.
  # use all_var variables in scripts.
  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/env/{{ env }}/vault.yml"
    - "./../../vars/env/{{ env }}/env.yml"
    - "./../../vars/all_var.yml"

  user: "{{ remote_user_account }}"
  gather_facts: no
  tasks:
  - name: ping all hosts
    ping:

  - name: "A quick shell echo {{ env }} / {{ vault_env_s3_bucket_account }} / {{ env_db_name }}"
    action: "shell /bin/echo $HOSTNAME in {{ env }} via {{ remote_user_account }}"

  - name: "Do something when there is an undefined variable"
    shell: "echo 'hello World {{ check_this_var| default('undefined') }}'"
    when: ( check_this_var is undefined ) or
          (( check_this_var is defined ) and ( check_this_var|lower == 'yes' ))