---
# File: test_role.yml 
# Created: 6/26/17
# Author: '@ekivemark'

# Playbook to:
#  - run a role file provided as a variable
#  -
#
# Based on: http://odecee.com.au/cloudformation-and-ansible/
# Vars file is relative to playbook file
# vars_files:
# Vars file is relative to playbook file
# Sequence:
# 1. Common variables
# 2. encrypted vault file
# 3. environment specific variables
# 4. all_vars which reference the preceding three files.
# common_ prefixes common variables
# vault_env_ prefixes encrypted variables
# env_ prefixes environment specific variables
# all_var incorporates preceding variables and defines variables without prefixes.
# use all_var variables in scripts.

- name: setup backups
  hosts: "{{ build_target }}"
  # connection: local
  remote_user: ec2-user
  gather_facts: True
  vars:
    env: "dev"
    azone: "az1"
    env_az: "{{ env }}-{{ azone }}"
    env_cf_data_version: "20"
    ansible_ssh_pipelining: no

  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/env/{{ env }}/vault.yml"
    - "./../../vars/env/{{ env }}/env.yml"
    - "./../../vars/all_var.yml"

  tasks:
# pass in test_this_role variable

   - include: "{{ test_this_role }}"