---
# File: /playbook/appherd/roles/create_self_signed_cert/tasks/main.yml
# Created: 11/28/17
# Author: '@ekivemark'

# Create a self signed certificate on appserver
# {{ apache_cert_store }} is typically set to  /etc/httpd/ssl/certs
# export CERT_STORE=/etc/httpd/ssl/certs

# based on: https://stackoverflow.com/questions/36182242/aws-elb-backend-server-over-https-with-self-signed-certificate


- name: "Self-Signed-Cert: Create {{ apache_cert_store }} "
  become_user: "{{ remote_admin_account }}"
  become: yes
  file:
    dest: "{{ apache_cert_store }}"
    mode: 0755
    owner: "root"
    group: "root"
    recurse: yes
    state: directory

- name: "check .pem file is not zero  length. If so, move to .pem.old"
  become_user: "{{ remote_admin_account }}"
  become: yes
  shell: "find {{ apache_cert_store }}/{{ item }} -empty  | xargs -I '{}' mv {} {}.old ; "
  with_items:
    - cert.pem
    - key.pem
    - fullchain.pem

- name: "Generate key, csr and cert pem for {{ external_dns_name }} in {{ apache_cert_store }}"
  become_user: "{{ remote_admin_account }}"
  become: yes
  command: |
    openssl req -new -nodes -x509 \
      -subj "/C=US/ST=Maryland/L=Baltimore`/O=OEDA/CN=$HOSTNAME" \
      -days 3650 \
      -keyout {{ apache_cert_store }}/key.pem \
      -out {{ apache_cert_store }}/cert.pem \
      -extensions v3_ca creates={{ apache_cert_store }}/cert.pem
  register: cert_create_result

# avoid an error launching apache by copying cert.pem to fullchain.pem
- name: "Copy {{ apache_cert_store }}/cert.pem to fullchain.pem"
  become_user: "{{ remote_admin_account }}"
  become: yes
  copy:
    remote_src: true
    src: "{{ apache_cert_store }}/cert.pem"
    dest: "{{ apache_cert_store }}/fullchain.pem"


- name: "checking results of self-cert creation "
  debug:
    msg: "result of cert create:\n {{ cert_create_result.stdout }}"