---
# File: /playbook/appherd/roles/create_self_signed_cert/tasks/main.yml
# Created: 11/28/17
# Author: '@ekivemark'

# Create a self signed certificate on appserver
# {{ apache_cert_store }} is typically set to  /etc/httpd/ssl/certs
# export CERT_STORE=/etc/httpd/ssl/certs

# based on: https://stackoverflow.com/questions/36182242/aws-elb-backend-server-over-https-with-self-signed-certificate


- name: "Self-Signed-Cert: Create {{ apache_cert_store }} "
  become_user: root
  become: yes
  file:
    dest: "{{ apache_cert_store }}"
    mode: 0755
    owner: "root"
    group: "root"
    recurse: yes
    state: directory

- name: "Generate key, csr and cert pem for {{ external_dns_name }} in {{ apache_cert_store }}"
  become_user: root
  become: yes
  command: |
    openssl req -new -nodes -x509 \
      -subj "/C=US/ST=Maryland/L=Baltimore`/O=OEDA/CN=${ansible_fqdn}" \
      -days 3650 \
      -keyout {{ apache_cert_store }}/key.pem \
      -out {{ apache_cert_store }}/cert.pem \
      -extensions v3_ca creates={{ apache_cert_store }}/cert.pem
