---
# File: main.yml 
# Created: 6/6/17
# Author: '@ekivemark'

# Setup Ansible Logging

- name: "create folder for ansible logs"
  file:
    dest: "/var/ansible/log"
    state: directory
    recurse: yes
    owner: root
    group: logreader
    mode: "0600"

- name: "touch logfile"
  file:
    dest: "/var/ansible/log/ansible.log"
    state: touch
    owner: root
    group: logreader
    mode: "0640"


