---
# File: build_fips140_database.yml
# Created: 5/4/17
# Author: @ekivemark

- name: Provision Database Server
  hosts: dbservers
  # connection: smart
  gather_facts: False
  user: ec2-user
  become_user: root
  become: yes
  # become_method: sudo
  vars:
    env: "dev"
    env_az: "{{ env }}-az1"
    splunk_client_name: "BBAPI-{{ env }}-DATA"

  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/env/{{ env }}/vault.yml"
    - "./../../vars/env/{{ env }}/env.yml"
    - "./../../vars/all_var.yml"

  roles:
    - ../../roles/base_patch
    - ../../roles/splunk
    - ../../roles/postgres

  tasks:
  - name: "pinging..."
    become_user: root
    ping:

  handlers:
    - ../../roles/postgres/handlers/main.yml