---
# File: create_database.yml 
# Created: 4/18/17

# Playbook to:
#  - create Postgres 9.x Database Server
#  - create App Server
#
# Based on: http://odecee.com.au/cloudformation-and-ansible/
# Vars file is relative to playbook file
# vars_files:
# Vars file is relative to playbook file
# Sequence:
# 1. Common variables
# 2. encrypted vault file
# 3. environment specific variables
# 4. all_vars which reference the preceding three files.
# common_ prefixes common variables
# vault_env_ prefixes encrypted variables
# env_ prefixes environment specific variables
# all_var incorporates preceding variables and defines variables without prefixes.
# use all_var variables in scripts.

- name: Provision Database
  hosts: "{{ build_target }}"
  # connection: local
  remote_user: ec2-user
  gather_facts: True
  vars:
    env: "dev"
    azone: "az1"
    env_az: "{{ env }}-{{ azone }}"
    env_cf_data_version: "20"
    splunk_client_name: "BBAPI-{{ env|upper }}-DATA"
    ansible_ssh_pipelining: no
  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/env/{{ env }}/vault.yml"
    - "./../../vars/env/{{ env }}/env.yml"
    - "./../../vars/all_var.yml"

  roles:
    - ../../roles/splunk
    # moved add_external_vol to its own playbook - attach_data_volume.yml
    # - ../../roles/add_external_vol
    - ../../roles/postgres

  tasks:


  - name: "Set Hostname to {{ cf_data_pgsql_server_name }} "
    remote_user: ec2-user
    become_user: root
    become: yes
    hostname:
      name: "{{ cf_data_pgsql_server_name }}"

