---
# File: build_fips140_database.yml
# Created: 5/4/17
# Author: @ekivemark

- name: Provision Database Server
  hosts: dbservers
  # connection: local
  # gather_facts: False
  vars:
    env: "dev"
    env_az: "{{ env }}-az1"
    splunk_client_name: "BB-{{ env }}-DATA"

  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/env/{{ env }}/vault.yml"
    - "./../../vars/env/{{ env }}/env.yml"
    - "./../../vars/all_var.yml"

#  roles:
#    - role: base

  tasks:
    - include: ../../roles/base/tasks/configure_splunk.yml
    - include: ../../roles/base/tasks/main.yml
