---
# File: create_fips140_base.yml
# Created: 5/3/17

# Playbook to:
#  - create base Server
#  - Apply FIPS 140.2
#
# Based on: http://odecee.com.au/cloudformation-and-ansible/
# Vars file is relative to playbook file
# vars_files:
# Vars file is relative to playbook file
# Sequence:
# 1. Common variables
# 2. encrypted vault file
# 3. environment specific variables
# 4. all_vars which reference the preceding three files.
# common_ prefixes common variables
# vault_env_ prefixes encrypted variables
# env_ prefixes environment specific variables
# all_var incorporates preceding variables and defines variables without prefixes.
# use all_var variables in scripts.

- name: Provision Server
  hosts: localhost
  connection: local
  # gather_facts: False
  vars:
    env: "dev"
    env_az: "{{ env }}-az1"
    env_cf_data_version: "04"

  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/env/{{ env }}/vault.yml"
    - "./../../vars/env/{{ env }}/env.yml"
    - "./../../vars/all_var.yml"

  tasks:
  - name: "launch base server for database"
    ec2:
      # connection: local
      # gather_facts: False
      # tags: provisioning
      # Necessary Variables for creating/provisioning the EC2 Instance
      #vars:
      # Adding instance_id list to see if only one server is created.
      # instance_ids: ["i-028b8fcc6eaf54779"]
      instance_type: "{{ cf_data_instance_type }}"
      # security_group:
      group: "BB-SG-DEV-DATA-ALLZONE" # Change the security group name here
      # This image should be updated monthly.
      # Current version is: EAST-RH 7-3 Gold Image V.1.09 (HVM) 04-21-2017 - ami-fdde41eb
      # EAST-RH 6-9 Gold Image V.1.01 (PV) 04-21-17 - ami-3dda452b
      image: "ami-fdde41eb" # Change the AMI, from which you want to launch the server

      key_name: "{{ cf_data_key_name }}" # Change the keypair name
      region: "us-east-1"
      # tenancy must be "dedicated"
      tenancy: "dedicated"
      # DEV AZ1 DATA
      vpc_subnet_id: "{{ common_cf_subnet[env_az][env_cf_data_tag_key_layer] }}"  # "subnet-8cecfba6"
      count: 1
      # state: present
      termination_protection: yes
      # tags to instance_tags
      instance_tags:
        Name: "bb-{{ env }}-{{ cf_data_azone }}-{{ env_cf_data_tag_key_layer }}-{{ env_cf_data_version }}"
        Stack: "BB-{{ env }}-{{ cf_data_azone }}-{{ env_cf_data_tag_key_layer }}-ansible"
        Business: "{{ cf_tags_business }}"
        Application: "{{ cf_tags_application }}"
        Environment: "{{ env }}"
        Function: "{{ cf_data_tag_key_layer }}-{{ cf_data_database_type }}"
    register: data_fips_output

  - name: "add private_ip to /etc/ansible/hosts"
    lineinfile:
      path: /etc/ansible/hosts
      regexp: "[dbservers]"
      line: "[dbservers]\n{{ data_fips_output.instances[0]['private_ip'] }}"
      backup: yes

