---
# File: create_database.yml 
# Created: 4/18/17

# Playbook to:
#  - create Postgres 9.x Database Server
#  - create App Server
#
# Based on: http://odecee.com.au/cloudformation-and-ansible/
# Vars file is relative to playbook file
# vars_files:
# Vars file is relative to playbook file
# Sequence:
# 1. Common variables
# 2. encrypted vault file
# 3. environment specific variables
# 4. all_vars which reference the preceding three files.
# common_ prefixes common variables
# vault_env_ prefixes encrypted variables
# env_ prefixes environment specific variables
# all_var incorporates preceding variables and defines variables without prefixes.
# use all_var variables in scripts.

- name: Provision Database
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    env: "dev"
  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/env/{{ env }}/vault.yml"
    - "./../../vars/env/{{ env }}/env.yml"
    - "./../../vars/all_var.yml"

  tasks:
  - name: "launch database server in CloudFormation"
    cloudformation:
      stack_name: "bb-{{ env }}-data-01"
      state: "present"
      region: "us-east-1"
      disable_rollback: true
      template: "../../templates/dataserver/vpc-pickenv-fe-fips-db-3.json"
      template_parameters:
        AZone: "{{ cf_data_azone }}"
        BuildImageId: "{{ cf_data_build_image_id }}"
        InstanceName: "{{ cf_data_instance_name }}"
        DatabaseType: "{{ cf_data_database_type }}"
        DatabasePrefix: "{{ cf_data_database_prefix }}"
        TagKeyStack: "{{ cf_data_tag_key_stack }}"
        TagKeyLayer: "{{ cf_data_tag_key_layer }}"
        KeyName: "{{ cf_data_key_name }}"
        InstanceType: "{{ cf_data_instance_type }}"
        PgsqlServerName: "{{ cf_data_pgsql_server_name }}"
        PyAppHome: "{{ cf_data_pyapps_home }}"
        PgsqlMaster: "{{ cf_data_pgsql_master }}"
        pyappsemail: "{{ cf_data_pyapps_email }}"
        PgsqlPassword: "{{ cf_data_pgsql_password }}"
        VpcId: "{{ cf_data_vpc_id }}"
      tags:
        Stack: "BB-{{ env }}-{{ cf_data_azone }}-{{ env_cf_data_tag_key_layer }}-ansible-cloudformation"
