---
# File: playbook/dataserver/set_backup_tasks.yml
# Created: 5/25/17
# Author: '@ekivemark'

- import_tasks: ../../roles/base_patch/tasks/set_db_aws_credentials.yml

- import_tasks: ./roles/update_awscli/tasks/main.yml

- import_tasks: ./roles/postgres/tasks/pgpass.yml

- import_tasks: ./roles/postgres/tasks/backup.yml

