---
- name: Install extras python3.8 (FROM JIMMY TEST BRANCH)
  become_user: "{{ remote_admin_account }}"
  become: yes
  command: "amazon-linux-extras install python3.8 -y"
- name: Install dependencies
  become: yes
  become_user: "{{ remote_admin_account }}"
  yum:
    name:
      - gcc
      - git
      - python38-devel
      - postgresql-devel
      - zlib-devel
      - libjpeg-turbo-devel
      - nginx
      - amazon-cloudwatch-agent
#      - yum-utils
#      - yum-plugin-versionlock
#- name: Establish Version Locking (BB2-3172)
#  shell:
#    cmd: |
#      yum versionlock add {{item}}
#  loop:
#    - grub2-2.06-14.amzn2.0.3*
#    - grub2-common-2.06-14.amzn2.0.3*
#    - grub2-pc-2.06-14.amzn2.0.3.*
#    - grub2-tools-2.06-14.amzn2.0.3
#    - grub2-tools-minimal-2.06-14.amzn2.0.3*
#    - grub2-tools-extra-2.06-14.amzn2.0.3*
#    - grub2-tools-efi-2.06-14.amzn2.0.3*
#- name: Apply security patches
#  become_user: "{{ remote_admin_account }}"
#  become: yes
#  command: "yum update-minimal --security -y"
- name: Install uwsgi ansible boto3 and botocore psycopg2-binary==2.9.6 via pip3.8
  become: yes
  become_user: "{{ remote_admin_account }}"
  pip:
    name:
      - uwsgi
      - ansible
      - boto3
      - botocore
      - psycopg2-binary==2.9.6
    executable: pip3.8
    umask: "0022"