---
- name: Apply security patches
  become_user: "{{ remote_admin_account }}"
  become: yes
  command: "yum update-minimal --security -y"
- name: List all topics in extras
  become_user: "{{ remote_admin_account }}"
  become: yes
  command: "amazon-linux-extras"
  register: all_extras_topics

- debug: var=all_extras_topics.stdout_lines

- name: Install extras python3.8
  become_user: "{{ remote_admin_account }}"
  become: yes
  command: "amazon-linux-extras install python3.8 -y"
- name: Install dependencies
  become: yes
  become_user: "{{ remote_admin_account }}"
  yum:
    name:
      - gcc
      - git
      - python3-devel
      - postgresql-devel
      - zlib-devel
      - libjpeg-turbo-devel
      - nginx
      - amazon-cloudwatch-agent
- name: Install uwsgi ansible boto3 and botocore via pip3
  become: yes
  become_user: "{{ remote_admin_account }}"
  pip:
    name: 
      - uwsgi
      - ansible
      - boto3
      - botocore
    executable: pip3
    umask: "0022"