---
- name: Apply security patches
  become: yes
  become_user: "{{ remote_admin_account }}"
  command: "dnf update --security -y"

- name: Install Python 3.11 and pip3.11
  become: yes
  become_user: "{{ remote_admin_account }}"
  command: "dnf install -y python3.11 python3.11-pip"

- name: Install system dependencies
  become: yes
  become_user: "{{ remote_admin_account }}"
  dnf:
    name:
      - gcc
      - make
      - openssl
      - openssl-devel
      - tar
      - wget
      - bzip2-devel
      - libffi-devel
      - git
      - python3.11-devel
      - postgresql-devel
      - postgresql16
      - sqlite-devel
      - zlib-devel
      - libjpeg-turbo-devel
      - nginx
      - amazon-cloudwatch-agent
    state: present

- name: Install wheel to support building packages
  become: yes
  become_user: "{{ remote_admin_account }}"
  pip:
    name: wheel
    executable: pip3.11

- name: Install uwsgi from GitHub to avoid setup.py issues
  become: yes
  become_user: "{{ remote_admin_account }}"
  pip:
    name: git+https://github.com/unbit/uwsgi.git
    executable: pip3.11

- name: Install ansible, boto3, botocore, and psycopg2-binary==2.9.10 via pip3.11
  become: yes
  become_user: "{{ remote_admin_account }}"
  pip:
    name:
      - ansible
      - boto3
      - botocore
      - psycopg2-binary==2.9.10
    executable: pip3.11
    umask: "0022"
