---
- name: Apply security patches
  become_user: "{{ remote_admin_account }}"
  become: yes
  command: "dnf update --security -y"  # Use dnf for AL2023, yum for AL2

- name: Install Python 3.11 and pip3.11
  become: yes
  become_user: "{{ remote_admin_account }}"
  command: "dnf install -y python3.11 python3.11-pip"  # Adjusted for AL2023

- name: Install dependencies
  become: yes
  become_user: "{{ remote_admin_account }}"
  dnf:
    name:
      - gcc
      - make
      - openssl
      - openssl-devel
      - tar
      - wget
      - bzip2-devel
      - libffi-devel
      - git
      - python3.11-devel  # Adjusted for AL2023
      - postgresql-devel
      - postgresql16
      - sqlite-devel
      - zlib-devel
      - libjpeg-turbo-devel
      - nginx
      - amazon-cloudwatch-agent
    state: present
- name: Install session-manager-plugin if not present
  become: yes
  become_user: "{{ remote_admin_account }}"
  shell: |
    if ! command -v session-manager-plugin &> /dev/null; then
      echo "Installing session-manager-plugin..."
      curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
      dpkg -i session-manager-plugin.deb
      rm -f session-manager-plugin.deb
    fi
  args:
    executable: /bin/bash
- name: Install uwsgi ansible boto3 and botocore psycopg2-binary==2.9.10 via pip3.11
  become: yes
  become_user: "{{ remote_admin_account }}"
  pip:
    name:
      - uwsgi
      - ansible
      - boto3
      - botocore
      - psycopg2-binary==2.9.10
    executable: pip3.11
    umask: "0022"
