---
- name: Apply security patches
  become_user: "{{ remote_admin_account }}"
  become: yes
  command: "yum update-minimal --security -y"
- name: Apply openssl patch - CVE-2022-1292
  become_user: "{{ remote_admin_account }}"
  become: yes
  command: "yum update openssl"
- name: Install dependencies
  become: yes
  become_user: "{{ remote_admin_account }}"
  yum:
    name:
      - gcc
      - git
      - python3-devel
      - postgresql-devel
      - zlib-devel
      - libjpeg-turbo-devel
      - nginx
      - amazon-cloudwatch-agent
- name: Install uwsgi ansible boto3 and botocore via pip3
  become: yes
  become_user: "{{ remote_admin_account }}"
  pip:
    name: 
      - uwsgi
      - ansible
      - boto3
      - botocore
    executable: pip3
    umask: "0022"