---
- name: Apply security patches
  become_user: "{{ remote_admin_account }}"
  become: yes
  command: "yum update-minimal --security -y"
- name: Install dependencies
  become: yes
  become_user: "{{ remote_admin_account }}"
  yum:
    name:
      - gcc
      - make
      - tar
      - wget
      - git
      - postgresql-devel
      - zlib-devel
      - libjpeg-turbo-devel
      - nginx
      - amazon-cloudwatch-agent
    state: present
- name: Install extras python3.11 on Amazon Linux 2
  become_user: "{{ remote_admin_account }}"
  become: yes
  get_url:
     url: https://www.python.org/ftp/python/3.11.0/Python-3.11.0.tgz
     dest: /usr/src/Python-3.11.0.tgz

- name: Extract Python 3.11 source
  become_user: "{{ remote_admin_account }}"
  unarchive:
     src: /usr/src/Python-3.11.0.tgz
     dest: /usr/src
     remote_src: yes
  become: yes
- name: Configure and install Python 3.11
  shell: |
     cd /usr/src/Python-3.11.0
     ./configure --enable-optimizations
     make altinstall
- name: Python3.11 is available in the path
  become_user: "{{ remote_admin_account }}"
  become: yes
  shell: ln -sf /usr/local/bin/python3.11 /usr/bin/python3.11
- name: Verify Python3.11 installation
  command: python3.11 --version
  register: python_version
- name: Install uwsgi ansible boto3 and botocore psycopg2-binary==2.9.6 via pip3.8
  become: yes
  become_user: "{{ remote_admin_account }}"
  pip:
    name:
      - uwsgi
      - ansible
      - boto3
      - botocore
      - psycopg2-binary==2.9.6
    executable: pip3.8
    umask: "0022"