---
- name: Apply security patches
  command: "yum update-minimal --security -y"
  become: yes
  # args:
  #   warn: false
  # register: yum_output
- name: Install dependencies
  yum:
    name:
      - gcc
      - git
      - python3-devel
      - postgresql-devel
      - zlib-devel
      - libjpeg-turbo-devel
      - nginx
      - amazon-cloudwatch-agent
  become: yes
- name: Install uwsgi ansible boto3 and botocore via pip3
  pip:
    name: 
      - uwsgi
      - ansible
      - boto3
      - botocore
    executable: pip3
    umask: "0022"
  become: yes