---
- name: Apply security patches
  become_user: "{{ remote_admin_account }}"
  become: yes
  command: "yum update-minimal --security -y"
- name: Install dependencies
  become: yes
  become_user: "{{ remote_admin_account }}"
  yum:
    name:
      - gcc
      - make
      - openssl-devel
      - tar
      - wget
      - bzip2-devel
      - libffi-devel
      - git
      - postgresql-devel
      - zlib-devel
      - libjpeg-turbo-devel
      - nginx
      - amazon-cloudwatch-agent
    state: present

- name: Install Python 3.11 and Pip
  hosts: all
  become: yes
  tasks:
    - name: Ensure Python 3.11 is installed
      command: python3.11 --version
      register: python_version
      failed_when: python_version.rc != 0

    - name: Print Python 3.11 version
      debug:
        msg: "Python 3.11 version is {{ python_version.stdout }}"
- name: Install uwsgi ansible boto3 and botocore psycopg2-binary==2.9.6 via pip3.11
  become: yes
  become_user: "{{ remote_admin_account }}"
  pip:
    name:
      - uwsgi
      - ansible
      - boto3
      - botocore
      - psycopg2-binary==2.9.6
    executable: /usr/bin/pip3.11
    umask: "0022"