---
- name: Apply security patches
  become: yes
  command: "yum update-minimal --security -y"
  args:
    warn: false
  register: yum_output
- name: Show yum security update output
  debug:
    var: yum_output
- name: Install dependencies
  become: yes
  yum:
    name:
      - gcc
      - git
      - python3-devel
      - postgresql-devel
      - zlib-devel
      - libjpeg-turbo-devel
      - nginx
      - amazon-cloudwatch-agent
- name: Install uwsgi ansible boto3 and botocore via pip3
  become: yes
  pip:
    name: 
      - uwsgi
      - ansible
      - boto3
      - botocore
    executable: pip3
    umask: "0022"