---
- name: Apply security patches
  command: "yum update-minimal --security -y"
  become: yes
- name: Install dependencies
  yum:
    name:
      - gcc
      - git
      - python3-devel
      - postgresql-devel
      - zlib-devel
      - libjpeg-turbo-devel
      - nginx
      - amazon-cloudwatch-agent
      - amazon-linux-extras
  become: yes

- name: enable python38 from amazon-extras repo
  command: "/usr/bin/amazon-linux-extras enable python3.8"
  become: yes

- name: install python38 from amazon-extras repo
  yum: 
    name:
      - python3.8
  become: yes

- name: Install uwsgi ansible boto3 and botocore via pip3
  pip:
    name: 
      - uwsgi
      - ansible
      - boto3
      - botocore
    executable: pip3
    umask: "0022"
  become: yes