---
- name: Apply security patches
  become_user: "{{ remote_admin_account }}"
  become: yes
  command: "yum update-minimal --security -y"
- name: Install extras python3.9
  become_user: "{{ remote_admin_account }}"
  become: yes
  command: "amazon-linux-extras install python3.9 -y"
- name: Install dependencies
  become: yes
  become_user: "{{ remote_admin_account }}"
  yum:
    name:
      - gcc
      - git
      - python39-devel
      - postgresql-devel
      - zlib-devel
      - libjpeg-turbo-devel
      - nginx
      - amazon-cloudwatch-agent
- name: Install uwsgi ansible boto3 and botocore psycopg2-binary==2.9.6 via pip3.9
  become: yes
  become_user: "{{ remote_admin_account }}"
  pip:
    name: 
      - uwsgi
      - ansible
      - boto3
      - botocore
      - psycopg2-binary==2.9.6
    executable: pip3.9
    umask: "0022"