---
- name: Apply security patches
  become_user: "{{ remote_admin_account }}"
  become: yes
  command: "yum update-minimal --security -y"
- name: Install dependencies
  become: yes
  become_user: "{{ remote_admin_account }}"
  yum:
    name:
      - gcc
      - make
      - openssl-devel
      - tar
      - wget
      - bzip2-devel
      - libffi-devel
      - git
      - postgresql-devel
      - zlib-devel
      - libjpeg-turbo-devel
      - nginx
      - amazon-cloudwatch-agent
    state: present

- name: Verify Python3.11 installation
  command: python3.11 --version
  register: python_version
- name: Install uwsgi ansible boto3 and botocore psycopg2-binary==2.9.6 via pip3.8
  become: yes
  become_user: "{{ remote_admin_account }}"
  pip:
    name:
      - uwsgi
      - ansible
      - boto3
      - botocore
      - psycopg2-binary==2.9.6
    executable: pip3.8
    umask: "0022"