---
- name: Apply security patches
  become_user: "{{ remote_admin_account }}"
  become: yes
  command: "yum update-minimal --security -y"
- name: Install dependencies
  become: yes
  become_user: "{{ remote_admin_account }}"
  yum:
    name:
      - gcc
      - make
      - openssl11
      - openssl11-devel
      - tar
      - wget
      - bzip2-devel
      - libffi-devel
      - git
      - postgresql-devel
      - zlib-devel
      - libjpeg-turbo-devel
      - nginx
      - amazon-cloudwatch-agent
    state: present

- name: Download python3 tar
  become: yes
  get_url:
    url: https://www.python.org/ftp/python/3.11.9/Python-3.11.9.tgz
    dest: /python3.tgz
- name: Extract python3.tgz
  become: yes
  unarchive:
          src: /python3.tgz
          dest: /
          creates: /Python-3.11.9
          remote_src: yes

    # NOTE: python is primarily used for infrastructure and operational support to BFD.
    #       Optimizations via `--enable-optimizations` in the `configure` step below are
    #       not enabled to avoid lengthy build times.
    #       https://docs.python.org/3/using/configure.html#performance-options
- name: Configure, make, make altinstall python3
  become: yes
  shell:
     cmd: |
      ./configure --with-openssl=/usr/ --enable-optimizations&& \
       make && \
       make altinstall
     chdir: /Python-3.11.9
     creates: /usr/local/bin/python3.11

- name: Create symbolic links
  become: yes
  file:
        src: "{{ item.src }}"
        path: "{{ item.path }}"
        state: link
        force: true
  loop:
        - src: /usr/local/bin/python3.11
          path: /usr/bin/python3
        - src: /usr/local/bin/pip3.11
          path: /usr/bin/pip3
- name: Upgrade pip3
  become: yes
  command: /usr/bin/python3 -m pip install --upgrade pip
- name: Install uwsgi ansible boto3 and botocore psycopg2-binary==2.9.6 via pip3.11
  become: yes
  become_user: "{{ remote_admin_account }}"
  pip:
    name:
      - uwsgi
      - ansible
      - boto3
      - botocore
      - psycopg2-binary==2.9.6
    executable: /usr/bin/pip3
    umask: "0022"