---
- name: Apply security patches
  become_user: "{{ remote_admin_account }}"
  become: yes
  command: "yum update-minimal --security -y"
- name: Cat iamge ID
  become_user: "{{ remote_admin_account }}"
  become: yes
  command: "cat /etc/image-id"
  register: out
- debug: var=out.stdout_lines
- name: Install dependencies added libs for python311 build
  become: yes
  become_user: "{{ remote_admin_account }}"
  yum:
    name:
      - gcc
      - git
      - postgresql-devel
      - zlib-devel
      - libjpeg-turbo-devel
      - nginx
      - amazon-cloudwatch-agent
      - openssl-devel
      - bzip2-devel
      - libffi-devel
      - zlib-devel
- name: Download python3.11.9 source tar ball
  become_user: "{{ remote_admin_account }}"
  become: yes
  command: "wget https://www.python.org/ftp/python/3.11.9/Python-3.11.9.tgz"
- name: Unpack python3.11.9 source tar ball
  become_user: "{{ remote_admin_account }}"
  become: yes
  command: "tar xzf Python-3.11.9.tgz"
- name: Build python3.11.9
  become_user: "{{ remote_admin_account }}"
  become: yes
  command: chdir=Python-3.11.9 {{ item }}
  with_items:
    - ./configure --enable-optimizations
    - which make
    - make clean
    - sudo make altinstall
  register: out2
- debug: var=out2.stdout_lines
- name: Cleanup and check version
  become_user: "{{ remote_admin_account }}"
  become: yes
  command: "rm -f Python-3.11.8.tgz ; python3.11 --version"
  register: out3
- debug: var=out3.stdout_lines
- name: Install pip with python 3.11.9
  become_user: "{{ remote_admin_account }}"
  become: yes
  command: "python3.11 -m ensurepip --upgrade"
  register: out4
- debug: var=out4.stdout_lines
- name: Install uwsgi ansible boto3 and botocore psycopg2-binary==2.9.6 via pip3.11
  become: yes
  become_user: "{{ remote_admin_account }}"
  pip:
    name:
      - uwsgi
      - ansible
      - boto3
      - botocore
      - psycopg2-binary==2.9.6
    executable: pip3.11
    umask: "0022"