---
- name: "fix umask"
  become: yes
  become_user: "{{ remote_admin_account }}"
  shell: |
    echo '
    # Use default RHEL umask setting
    if ! shopt -q login_shell ; then
        if [ $UID -gt 199 ] && [ "$(/usr/bin/id -gn)" = "$(/usr/bin/id -un)" ]; then
            umask 002
        else
            umask 022
        fi
    fi
    ' | sudo tee -a /etc/bashrc

    echo '
    # Use default RHEL umask setting
    if [ $UID -gt 199 ] && [ "$(id -gn)" = "$(id -un)" ]; then
        umask 002
    else
        umask 022
    fi
    ' | sudo tee -a /etc/profile
  args:
    executable: /bin/bash

- name: "kill yum"
  become: yes
  become_user: "{{ remote_admin_account }}"
  shell: |
    kill "$(cat /var/run/yum.pid)"
  ignore_errors: yes

- name: "disable boot-time yum update"
  become: yes
  become_user: "{{ remote_admin_account }}"
  lineinfile:
    dest: /etc/cloud/cloud.cfg
    state: absent
    regexp: '^.*yum\s-y\supdate.*$'

- name: "fix sudoers file"
  import_tasks: ./fix_sudoers.yml

- name: "apply security patches"
  become_user: "{{ remote_admin_account }}"
  become: yes
  shell: yum update-minimal --security -y

- name: "add amazon ntp server to chrony.conf"
  lineinfile:
    path: /etc/chrony.conf
    insertafter: EOF
    line: 'server 169.254.169.123 prefer iburst'
  become: yes

- name: "restart chronyd"
  service:
    name: chronyd
    state: restarted
  become: yes
