---
# File: roles/base_patch/tasks/main.yml
# Created: 5/4/17
# Author: @ekivemark

- name: "fix sudoers file"
  import_tasks: ./fix_sudoers.yml

- name: "apply security patches"
  become_user: "{{ remote_admin_account }}"
  become: yes
  shell: yum update-minimal --security -y

- name: "add amazon ntp server to chrony.conf"
  lineinfile:
    path: /etc/chrony.conf
    insertafter: EOF
    line: 'server 169.254.169.123 prefer iburst'
  become: yes

- name: "restart chronyd"
  service:
    name: chronyd
    state: restarted
  become: yes
