---
# File: roles/base/main.yml
# Created: 5/4/17
# Author: @ekivemark
# Source: http://blog.programster.org/ansible-update-and-reboot-if-required-amazon-linux-servers/

- name: Copy sudoers file for safety
  become_user: root
  command: "cp -f /etc/sudoers /etc/sudoers.tmp"

- name: Create sudoers file backup
  become_user: root
  command: "cp -f /etc/sudoers /etc/sudoers.${date}.bak"

- name: "patch sudoers file"
  become_user: root
  vars:
    ansible_ssh_pipelining: no
  lineinfile:
    dest: /etc/sudoers.tmp
    line: 'Defaults   requiretty'
    state: absent

- name: Final sudoers file check
  become_user: root
  shell: visudo -q -c -f /etc/sudoers.tmp && cp -f /etc/sudoers.tmp /etc/sudoers

- name: "clean up /root for dataservers"
  become_user: root
  file:
    dest: /root/fips_140_2_update.log.*
    state: absent

- name: "upgrade all packages"
  become_user: root
  yum:
    name: "*"
    state: latest

- name: Check for reboot hint.
  shell: LAST_KERNEL=$(rpm -q --last kernel | perl -pe 's/^kernel-(\S+).*/$1/' | head -1); CURRENT_KERNEL=$(uname -r); if [ $LAST_KERNEL != $CURRENT_KERNEL ]; then echo 'reboot'; else echo 'no'; fi
  ignore_errors: true
  register: reboot_hint

- name: "Write aws config file"
  become_user: root
  template:
    src: "../templates/root_aws_config.js"
    dest: "/root/.aws/config"
    backup: yes
    owner: root
    group: root
    mode: "u+r"

- name: "write aws credentials"
  become_user: root
  template:
    src: "../templates/root_aws_credentials.j2"
    dest: "/root/.aws/credentials"
    owner: root
    group: root
    mode: "u+r"

- name: "Rebooting ..."
  command: shutdown -r now "Reboot required for updated kernel"
  async: 0
  poll: 0
  become_user: root
  ignore_errors: true
  when: reboot_hint.stdout.find("reboot") != -1
  register: rebooting

- name: "Wait for thing to reboot..."
  pause: seconds=45
  when: rebooting|changed

