---
# File: set_aws_credentials.yml 
# Created: 5/9/17
# Author: '@ekivemark'


- name: "Write aws config file"
  become_user: root
  template:
    src: "../templates/root_aws_config.js"
    dest: "/root/.aws/config"
    backup: yes
    owner: root
    group: root
    mode: "u+r"

- name: "write aws credentials"
  become_user: root
  template:
    src: "../templates/root_aws_credentials.j2"
    dest: "/root/.aws/credentials"
    owner: root
    group: root
    mode: "u+r"
