---
- name: "Write .env file"
  become_user: "{{ remote_admin_account }}"
  become: yes
  template:
    src: templates/env.j2
    dest: "{{ install_root }}/.env"
    owner: "{{ app_owner }}"
    group: "{{ app_group }}"
    mode: 0664
