---
# File: playbook/appserver/roles/create_superuser/tasks/main.yml
# Created: 5/15/17
# Author: '@ekivemark'

# check for superuser and if not exist create it.
# Bug fix - wrap password in quotes to avoid special characters eg. ! being changed.

# Get superuser count with:
## print(User.objects.filter(is_superuser=True).count())
# Check superuser exists (True/"") with:
## print(User.objects.filter(username='{{ cf_app_pyapps_user }}').count()>0)
##### Returning count
# or with count returned(nn):
## print(User.objects.filter(username='{{ cf_app_pyapps_user }}').count())


- name: setup intermediate folder
  become_user: root
  become: yes
  file:
    dest: "{{ cf_app_pyapp_home }}/output"
    owner: root
    group: root
    mode: "0700"
    state: directory

- name: setup intermediate result file
  become_user: root
  become: yes
  file:
    dest: "{{ cf_app_pyapp_home }}/output/su_result.txt"
    mode: "0750"
    owner: root
    group: root
    state: touch

- name: "does superuser exist?"
  become_user: root
  become: yes
  command:  |
    cd {{ cf_app_pyapp_home }}/{{ common_project_name }}
    echo "from django.contrib.auth import get_user_model; User = get_user_model(); print(User.objects.filter(username='{{ cf_app_pyapps_user }}').count())" | {{ cf_app_py_virtual_env }}/bin/python ./manage.py shell > {{ cf_app_pyapp_home }}/output/su_result.txt
  args:
    chdir: "{{ cf_app_pyapp_home }}/{{ common_project_name }}"
  environment:
    DJANGO_SETTINGS_MODULE: "{{ django_settings_module }}"

- name: check su_result.txt
  become_user: root
  become: yes
  command: "cat {{ cf_app_pyapp_home }}/output/su_result.txt  | grep \">>>\" | cut -d ' ' -f 2 "
  register: superuser_count

- name: "Create super user and set password"
  become_user: root
  become: yes
  shell: |
    cd {{ cf_app_pyapp_home }}/{{ common_project_name }}
    export DJANGO_SUPERUSER_USERNAME={{ cf_app_pyapps_user }}
    export DJANGO_SUPERUSER_PASSWORD='{{ cf_app_pyapps_pwd }}'
    export DJANGO_SUPERUSER_EMAIL={{ cf_app_pyapps_email }}
    # create Superuser
    {{ cf_app_py_virtual_env }}/bin/python3 ./manage.py create_super_user_from_envars
    # remove superuser variables
    export DJANGO_SUPERUSER_USERNAME=''
    export DJANGO_SUPERUSER_PASSWORD=''
    export DJANGO_SUPERUSER_EMAIL=''
  # when: not superuser_existed.stdout
  when: ( superuser_count.stdout == "0" )

- name: "does superuser exist now?"
  become_user: root
  become: yes
  command:  |
    cd {{ cf_app_pyapp_home }}/{{ common_project_name }}
    echo "from django.contrib.auth import get_user_model; User = get_user_model(); print(User.objects.filter(username='{{ cf_app_pyapps_user }}').count())" | {{ cf_app_py_virtual_env }}/bin/python ./manage.py shell > {{ cf_app_pyapp_home }}/output/su_result.txt
  args:
    chdir: "{{ cf_app_pyapp_home }}/{{ common_project_name }}"
  environment:
    DJANGO_SETTINGS_MODULE: "{{ django_settings_module }}"

- name: check su_result.txt
  become_user: root
  become: yes
  command: "cat {{ cf_app_pyapp_home }}/output/su_result.txt  | grep \">>>\" | cut -d ' ' -f 2 "
  register: superuser_made_count


- name: "was superuser created?"
  become_user: root
  become: yes
  command: "cat {{ cf_app_pyapp_home }}/output/su_result.txt  | grep \">>>\" | cut -d ' ' -f 2 "
  register: superuser_made_count

- name: "superuser count"
  debug:
    msg: "Superuser count = {{ superuser_made_count.stdout }}"
