---
# File: roles/apache/main.yml
# Created: 5/9/17
# Author: '@ekivemark'

- name: "Install supporting packages"
  include: ../../base_patch/tasks/app_server_tools.yml

- name: "Install Apache (httpd)"
  become_user: root
  become: yes
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - httpd
    - mod_ssl

#- name: "Create Virtualhosts file"
#  become_user: root
#  become: yes
#  template:
#    src: ../templates/virtualhost_server_conf.j2
#    dest: "/etc/httpd/conf.d/virtualhost.conf"
#    owner: root
#    group: root
#    mode: "0644"

- name: "Setup docs directory for server"
  become_user: root
  become: yes
  file:
    dest: "/var/www/doc/{{ cf_app_pyserver_name|lower }}"
    owner: root
    group: root
    state: directory
    mode: "0755"

- name: "Copy Wsgi Load Module instruction in to place"
  become_user: root
  become: yes
  copy:
    src: "../files/wsgi.conf"
    # rhel 7 apache 2.4 configuration
    dest: "/etc/httpd/conf.modules.d/10-wsgi.conf"
    owner: root
    group: root
    mode: "0644"


- name: "Check Apache is running"
  become_user: root
  become: yes
  service:
    name: httpd
    state: running
    enabled: yes

