---
- name: "configure splunk"
  become_user: "{{ remote_admin_account }}"
  become: yes
  template:
    src: "../templates/splunk_deployment_conf.j2"
    dest: "/opt/splunkforwarder/etc/system/local/deploymentclient.conf"

- name: "Stop and initialize splunk configuration"
  become_user: "{{ remote_admin_account }}"
  become: yes
  shell: |
    systemctl stop SplunkForwarder.service
    /opt/splunkforwarder/bin/splunk clone-prep-clear-config

- name: "Start splunk"
  become_user: "{{ remote_admin_account }}"
  shell: |
    systemctl start SplunkForwarder.service
