---
- name: "configure splunk"
  become_user: "{{ remote_admin_account }}"
  become: yes
  template:
    src: "../templates/splunk_deployment_conf.j2"
    dest: "/opt/splunkforwarder/etc/system/local/deploymentclient.conf"

- name: "Stop and initialize splunk configuration"
  become_user: "{{ remote_admin_account }}"
  become: yes
  shell: |
    /opt/splunkforwarder/bin/splunk stop
    /opt/splunkforwarder/bin/splunk clone-prep-clear-config

- name: "Start splunk"
  become_user: "{{ remote_admin_account }}"
  shell: |
    /opt/splunkforwarder/bin/splunk start --answer-yes --no-prompt --accept-license
    /opt/splunkforwarder/bin/splunk stop
    /opt/splunkforwarder/bin/splunk enable boot-start -user splunk
    /opt/splunkforwarder/bin/splunk restart