---
# File: roles/splunk/main.yml
# Created: 5/4/17
# Author: '@ekivemark'

- name: "Configure Splunk ..."
  become_user: root
  become: yes
  template:
    src: "../templates/splunk_deployment_conf.j2"
    dest: "/opt/splunkforwarder/etc/system/local/deploymentclient.conf"
    owner: splunk
    group: splunk
    mode: "750"
    backup: yes

# Replacing patch with template
#  become_user: root
#  become: yes
#  lineinfile:
#    dest: "/opt/splunkforwarder/etc/system/local/deploymentclient.conf"
#    owner: splunk
#    group: splunk
#    mode: "750"
#    regexp: "^clientName"
#    line: "clientName = {{ splunk_client_name }}"
#    backup: yes


- name: "Restart Splunk "
  become_user: root
  become: yes
  command: "/opt/splunkforwarder/bin/splunk restart"
  register: splunk_status



