---
# File: roles/splunk/main.yml
# Created: 5/4/17
# Author: '@ekivemark'

- name: "Stop Splunk "
  become_user: splunk
  become: yes
  command: "/opt/splunkforwarder/bin/splunk stop"
  register: splunk_status

- name: "get last octet of ip address"
  shell: "export last_ip_octet=$(/usr/sbin/ip route get 8.8.8.8 | /usr/bin/awk -F. '{print $NF;exit}') ; echo $last_ip_octet "
  register: app_ip_last_octet

- name: "octect number"
  debug:
    msg: "app_ip_last_octet ={{ app_ip_last_octet.stdout }}"

- name: "Configure Splunk ..."
  become_user: root
  become: yes
  template:
    src: "../templates/splunk_deployment_conf.j2"
    dest: "/opt/splunkforwarder/etc/system/local/deploymentclient.conf"
    owner: splunk
    group: splunk
    mode: "750"
    backup: yes

- name: "Initialize splunk configuration"
  become_user: splunk
  become: yes
  shell: |
    cd /opt/splunkforwarder/bin
    ./splunk clone-prep-clear-config

- name: "Restart Splunk - if this steps fails to complete Splunk may require license acceptance on host"
  become_user: root
  become: yes
  command: "/opt/splunkforwarder/bin/splunk restart"
  register: splunk_status



