---
# File: roles/splunk/main.yml
# Created: 5/4/17
# Author: '@ekivemark'

- name: "Configure Splunk ..."
  become_user: root
  become: yes
  ini_file:
    dest: /opt/splunkforwarder/etc/system/local/deploymentclient.conf
    owner: splunk
    group: splunk
    mode: u+rwx
    section: "deployment-client"
    option: clientName
    value: "{{ splunk_client_name }}"
    # backup: yes
