---
# File: roles/splunk/main.yml
# Created: 5/4/17
# Author: '@ekivemark'

- name: "Configure Splunk ..."
  become_user: splunk
  ini_file:
    path: "/opt/splunkforwarder/etc/system/local/deploymentclient.conf"
    section: "deployment-client"
    option: clientName
    value: "{{ splunk_client_name }}"
    backup: yes
