---
# File: playbook/mgmtserver/roles/root_cert/tasks/main.yml
# Created: 6/15/17
# Author: '@ekivemark'

# Create Root Key and sign the root certificate

- name: "Create a root key"
  become_user: root
  become: yes
  shell: |
    cd /root/ca
    echo {{ ca_rootca_password }}> /root/ca/{{ env }}_passphrase.txt
    openssl genrsa -aes256 -out private/{{ env }}_db_root_ca.key -passout file:/root/ca/{{ env }}_passphrase.txt 2048

- name: "Sign the root "
  become_user: root
  become: yes
  shell: |
    cd /root/ca
    export CA_ROOT_INP=/root/ca
    echo "US" >$CA_ROOT_INP/{{ env }}_cert_in.txt
    echo "Maryland" >>$CA_ROOT_INP/{{ env }}_cert_in.txt
    echo "Baltimore" >>$CA_ROOT_INP/{{ env }}_cert_in.txt
    echo "Centers for Medicare and Medicaid Services" >>$CA_ROOT_INP/{{ env }}_cert_in.txt
    echo "BlueButton on FHIR API Root CA" >>$CA_ROOT_INP/{{ env }}_cert_in.txt
    echo "BlueButton Root CA" >>$CA_ROOT_INP/{{ env }}_cert_in.txt
    echo "mark.scrimshire@cms.hhs.gov" >>$CA_ROOT_INP/{{ env }}_cert_in.txt
    echo " " >>$CA_ROOT_INP/{{ env }}_cert_in.txt
    openssl req -config ./openssl.cnf -key private/{{ env }}_db_root_ca.key -new -x509 -days 10950 -sha256 -extensions v3_ca -out certs/{{ env }}_db_root_ca.cert.pem <$CA_ROOT_INP/{{ env }}_cert_in.txt

