---
# File: roles/nessus_update_key/tasks/main.yml
# Created: 12/5/17
# Author: '@ekivemark'

# Apply public key to nessus_service account

- name: "Create the .ssh folder for {{ mon_nessus_user }}"
  become_user: "{{ remote_admin_account }}"
  become: yes
  file:
    dest: "/home/{{ mon_nessus_user }}/.ssh"
    mode: "0700"
    owner: "{{ mon_nessus_user }}"
    group: "{{ mon_nessus_user }}"
    state: directory

- name: "Create/touch the .ssh/authorized_keys file"
  become_user: "{{ remote_admin_account }}"
  become: yes
  file:
    dest: "/home/{{ mon_nessus_user }}/.ssh/authorized_keys"
    mode: "0600"
    owner: "{{ mon_nessus_user }}"
    group: "{{ mon_nessus_user }}"
    state: touch

- name: "Add the public key to authorized_keys"
  become_user: "{{ remote_admin_account }}"
  become: yes
  lineinfile:
    dest: "/home/{{ mon_nessus_user }}/.ssh/authorized_keys"
    state: present
    mode: "0600"
    owner: "{{ mon_nessus_user }}"
    group: "{{ mon_nessus_user }}"
    line: "{{ mon_nessus_pub_key }}"
    backup: yes

- name: "Check the authorized_keys file"
  become_user: "{{ remote_admin_account }}"
  become: yes
  shell: "cat /home/{{ mon_nessus_user }}/.ssh/authorized_keys"
  register: auth_keys_out

- name: "authorized_keys result"
  debug:
    msg: "{{ auth_keys_out.stdout.split('\n') }}"
