---
- name: Copy cloudwatch agent app logs config
  become_user: "{{ remote_admin_account }}"
  become: yes
  template:
    src: templates/cwagent-app.json.j2
    dest: /tmp/cwagent-app.json

- name: Reconfigure cloudwatch agent with app logs config
  become_user: "{{ remote_admin_account }}"
  become: yes
  shell: "/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a append-config -m ec2 -c file:/tmp/cwagent-app.json -s"

- name: Restart cloudwatch agent
  become_user: "{{ remote_admin_account }}"
  become: yes
  service:
    name: amazon-cloudwatch-agent
    state: restarted
