---
- name: "install mod_wsgi"
  become: yes
  become_user: "{{ remote_admin_account }}"
  shell: |
   source {{ cf_app_py_virtual_env }}/bin/activate && pip install mod_wsgi==4.6.4
  environment:
    APXS: /bin/apxs

- name: "capture wsgi configuration"
  become: yes
  become_user: "{{ remote_admin_account }}"
  shell: |
    source {{ cf_app_py_virtual_env }}/bin/activate && mod_wsgi-express module-config
  register: mod_wsgi_conf

- name: "install wsgi.conf"
  become_user: "{{ remote_admin_account }}"
  become: yes
  template:
    src: "wsgi.conf.j2"
    dest: "/etc/httpd/conf.modules.d/10-wsgi.conf"
    owner: root
    group: root
    mode: "0644"
