plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  tag:Function: app-AppServer

hostnames:
  - instance_id

compose:
  ansible_host: instance_id  # 🔥 required for SSM to work

vars:
  ansible_connection: amazon.aws.aws_ssm
  ansible_python_interpreter: /usr/bin/python3.9
  ansible_ssm_bucket_name: ''

keyed_groups:
  - key: tags.Function
    prefix: tag_Function
    separator: _
