plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  tag:Function: app-AppServer
hostnames:
  - private-ip-address
compose:
  ansible_host: private_ip_address
keyed_groups:
  - key: tags.Function
    prefix: tag_Function
    separator: _
vars:
  ansible_connection: amazon.aws.aws_ssm
  ansible_aws_ssm_profile: default