---
# File: roles/app_env/handlers/main.yml
# Created: 5/10/17
# Author: '@ekivemark'

- name: restart apache
  become_user: "{{ remote_admin_account }}"
  become: yes
  service:
    name: httpd
    state: restarted


