---
- name: Make sure ansible is installed on the target
  become_user: "{{ remote_admin_account }}"
  become: yes
  shell: pip install --upgrade ansible

- name: Copy env var playbook to target
  become_user: "{{ remote_admin_account }}"
  become: yes
  copy:
    src: files/env_vars.yml
    dest: "{{ install_root }}/env_vars.yml"
    mode: 0664
