---
- name: Write .env file
  become_user: "{{ remote_admin_account }}"
  become: yes
  template:
    src: "{{ root_lookup.files[0].path | dirname }}/roles/env_vars/templates/env.j2"
    dest: "{{ install_root }}/.env"
    owner: "{{ app_owner }}"
    group: "{{ app_group }}"
    mode: 0640

- name: Restart uwsgi
  become_user: "{{ remote_admin_account }}"
  become: yes
  service:
    name: uwsgi
    state: restarted

- name: Restart nginx
  become_user: "{{ remote_admin_account }}"
  become: yes
  service:
    name: nginx
    state: restarted
