---
- name: "Create the app log directory "
  become_user: "{{ remote_admin_account }}"
  become: yes
  file:
    dest: "{{ app_log_dir }}"
    owner: "{{ app_pyapps_user }}"
    group: logreader
    state: directory
    mode: 0775

# Logs need to be given group ownership to logreader
- name: "Create the logs"
  become_user: "{{ remote_admin_account }}"
  become: yes
  file:
    dest: "{{ app_log_dir }}/{{ item }}"
    owner: "{{ app_pyapps_user }}"
    group: logreader
    state: touch
    mode: 0776
  with_items:
    - debug.log
    - error.log
    - info.log
    - login_failed.log
    - admin_access.log
    - perf_mon.log

# SELinux disabled in Amazon Linux 2
- name: "Set permissions for SELinux"
  become_user: "{{ remote_admin_account }}"
  become: yes
  sefcontext:
    target: "{{ app_log_dir }}(/.*)?"
    setype: httpd_sys_content_t
    state: present
  ignore_errors: True
  when: platinum_source != "amzn2"

- name: "Setup log rotation for pyapps logs"
  become_user: "{{ remote_admin_account }}"
  become: yes
  copy:
    dest: "/etc/logrotate.d/pyapps"
    content: |
      {{ app_log_dir }}/*.log {
      missingok
      notifempty
      compress
      size 10M
      rotate 10
      copytruncate
      daily
      create 0776 {{ app_pyapps_user }} logreader
      }
    owner: root
    group: logreader
    mode: 0600
