---
# File: /playbook/appherd/0_prepare_ami.yml
# Created: 11/29/17
# Author: '@ekivemark'

# AMI Images are updated every month
# We need to make sure we build from the latest image
# On the Appserver we need to switch off the fips setting to avoid problems
# with installation and configuration.

# The process here is:
# 1. Get the latest Gold Image AMI
# 2. determine if image has been updated
# 3. Launch the image
# 4. Switch off FIPS and reboot the server
# 5. Create an AMI from the image
# 6. Save the ami image id to use in 1_create_appserver.yml


- name: Provision Server
  hosts: localhost
  connection: local
  # gather_facts: False
  vars:
    region: "us-east-1"
    ami_image_name: "EAST?RH?7?4*"
    env: "test"
    azone: "az2"
    sub_zone: "app"
    sg_zone: "app"
    env_az: "{{ env }}-{{ azone }}"
    env_cf_data_version: "01"
    # splunk_target_layer: "WEB | APP | DATA | MGMT"
    splunk_target_layer: "{{ sub_zone|upper }}"
  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/env/{{ env }}/vault.yml"
    - "./../../vars/env/{{ env }}/env.yml"
    - "./../../vars/all_var.yml"
    # write the ami image information to a file in /root
    # variable will be: current_app_ami_source
    - [ "/root/.ansible_app_ami.yml", "./../../vars/empty.yml" ]

  tasks:
  - name: "get list of suitable images"
    ec2_ami_find:
      name: "{{ ami_image_name }}"
      region: "{{ region }}"
      # value of sort must be one of:
      #   name,description,tag,architecture,block_device_mapping,creationDate,
      #   hypervisor,is_public,location,owner_id,platform,root_device_name,
      #   root_device_type,state,virtualization_type
      sort: creationDate
      sort_order: descending
    register: latest_ami

  - set_fact:
      build_from_ami: "{{ latest_ami.results[0].ami_id }}"

  - set_fact:
      existing_source_ami: "{{ current_app_ami_source | default('not_defined') }}"

  - set_fact:
      build_new_ami:  "{{ build_from_ami ==  existing_source_ami }}"
      cacheable: true

  - name: "Save the ami variable - currently undefined"
    shell: |
      echo current_app_ami_source: {{ build_from_ami }} > /root/.ansible_app_ami.yml
    when: ( current_app_ami_source is undefined )

  - debug:
      msg: "app_ami_source: {{ current_app_ami_source }} / build_from_ami: {{ build_from_ami }}\n build_new_ami: {{ build_new_ami }}"

  # switch off fips and save new image
  - include_tasks: ../../roles/fips140_off/tasks/main.yml
    when: ( current_app_ami_source is undefined ) or ( current_app_ami_source != build_from_ami )


