---
# File: playbook/appherd/300_refresh_server_code.yml
# Created: 5/9/17
# Author: '@ekivemark'

# Playbook to:
#  - create Python3/Django AppServer
#  - Take server in appservers and reapply python/django components.


#
# Based on: http://odecee.com.au/cloudformation-and-ansible/
# Vars file is relative to playbook file
# vars_files:
# Vars file is relative to playbook file
# Sequence:
# 1. Common variables
# 2. encrypted vault file
# 3. environment specific variables
# 4. all_vars which reference the preceding three files.
# common_ prefixes common variables
# vault_env_ prefixes encrypted variables
# env_ prefixes environment specific variables
# all_var incorporates preceding variables and defines variables without prefixes.
# use all_var variables in scripts.

# new base machines will be in appservers-base in /etc/ansible/hosts
# add all the base software and move the server to appservers and
# remove from appservers-base

- name: Refresh App Server
  # hosts: appservers
  hosts: "{{ build_target | default('appservers') }}"
  # connection: local
  remote_user: ec2-user
  # become_user: root
  # become: yes
  gather_facts: True
  vars:
    ansible_ssh_pipelining: no
    # The variables in this section can all be overridden in the vars_files
    # that follow
    env: "test"
    azone: "az1"
    sub_zone: "app"
    sg_zone: "appserver"
    env_az: "{{ env }}-{{ azone }}"
    env_cf_app_version: "01"
    # splunk_target_layer: "WEB | APP | DATA | MGMT"
    splunk_target_layer: "{{ sub_zone|upper }}"
    migrate: "yes"
    collectstatic: "yes"
    # Setting the playbook value for SNS Notifications
    sns_playbook: "playbook/appserver/build_appserver.yml"
    sns_subject: "rebuild appserver"
    sns_playbook_action: "rebuild"
    sns_debug: false
  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/env/{{ env }}/vault.yml"
    - "./../../vars/env/{{ env }}/env.yml"
    - "./../../vars/all_var.yml"

  # ../../roles/ points to roles stored in roles at the top level
  # - roles/ indicates the role is in this playbook directory

  roles:

    # Create the pyapps logs
    # Group ownership must go to logreader to enable splunk log capture
    - roles/app_logs

    # install swagger-ui from git
    # Used to present api documentation
    - roles/swagger_ui_install

    # prepare the folders for app install and log files
    - roles/app_prep

    # Install assigned Certs
    - roles/copy_issued_cert

    # Update application code and write virtualhosts file
    # Download from github
    # install requirements
    - roles/app_update

    # Setup logrotate rules for pyapps
    # Ensure logs belong to group: logreader
    - roles/log_rotate

    # Create apache cert_store
    # create directory in /etc/httpd/ssl/certs
    - roles/create_apache_cert_store

    # Install the certs to the cert_store for FHIR Backend requests
    - roles/install_fhircerts_to_store

    # Update environment variable files
    - roles/app_update_env

    # django migrate and collectstatic
    - roles/django_prep

    # Set permissions for app under selinux
    - roles/semanage_apps

    # Set permissions for virtualenv under selinux
    - roles/semanage_virtualenv

  tasks:

  # Create a super user for the python/django application
  - import_tasks: roles/create_superuser/tasks/main.yml

  - name: make sure apache server is running
    service:
      name: httpd
      state: started
      enabled: yes

  - name: "Restart Apache on {{ env }}"
    action: shell /bin/echo $HOSTNAME
    notify:
      - restart apache

  # Check if server is responding
  - name: "call with curl to localhost"
    shell: "curl https://localhost/"
    register: curl_output
    ignore_errors: yes

  - name: "Result of curl was..."
    debug:
      msg: "{{ curl_output.stdout }}"


  - name: "Add in to Loadbalancer"
    import_tasks: roles/attach_to_elb/tasks/main.yml

  - name: "Notify completion result"
    import_tasks: "../../roles/send_notification/tasks/main.yml"

  handlers:
  - name: restart apache
    become_user: root
    become: yes
    service: name=httpd state=restarted

  # Now We should have a working machine
  # Apache / Mod_Wsgi / Python3

