---
# File: playbook/appherd/roles/django_export_model/tasks/main.yml
# Created: 5/26/17
# Author: '@ekivemark'

# Perform django management command to export a model as csv
# add in group create for first run only.

- name: "Django export {{ export_model }}"
  become_user: "{{ remote_admin_account }}"
  become: yes
  # We only want to run the command on one server in the fleet
  run_once: yes
  shell: |
    cd {{ cf_app_pyapp_home }}/{{ common_project_name }}
    source {{ cf_app_py_virtual_env }}/bin/activate
    export PATH={{ cf_app_py_virtual_env }}/bin:$PATH
    ./manage.py "model2csv --application {{ export_application }} --model {{ export_model }} --add_table_name True >>{{ cf_app_log_dir }}/export.log"
  when: ( export_model is defined )

