---
# File: roles/app_env/tasks/app_logs.yml
# Created: 5/15/17
# Author: '@ekivemark'
# Create the App logging directory and touch the app logs

- name: "Create the app log directory "
  become_user: root
  become: yes
  file:
    dest: "{{ cf_app_log_dir }}"
    owner: root
    group: logreader
    state: directory
    mode: 0775

- name: "Create the logs"
  become_user: root
  become: yes
  file:
    dest: "{{ cf_app_log_dir }}/{{ item }}"
    owner: "{{ cf_app_pyapps_user }}"
    group: "logreader"
    state: touch
    mode: 0776
  with_items:
    - debug.log
    - error.log
    - info.log
    - perf_mon.log


