---
# File: roles/app_env/tasks/main.yml
# Created: 5/10/17
# Author: '@ekivemark'
# Create the application environment

- name: " Create the virtualenv folder"
  become_user: root
  become: yes
  file:
    dest: "/var/virtualenv"
    owner: pyapps
    group: pyapps
    mode: 0755
    state: directory

- name: " Create the app folder"
  become_user: root
  become: yes
  file:
    dest: "/var/pyapps"
    owner: pyapps
    group: pyapps
    mode: 0755
    state: directory

- name: "Create Virtualenv"
  become_user: root
  become: yes
  command: "cd /var/virtualenv ; {{ item }} "
  with_items:
    - /usr/local/bin/pyvenv-3.5 hhs_o_server

