---
# File: roles/app_env/tasks/main.yml
# Created: 5/10/17
# Author: '@ekivemark'
# Create the application environment

- name: " Create the virtualenv folder"
  become_user: root
  become: yes
  file:
    dest: "/var/virtualenv"
    owner: "{{ cf_app_pyapps_user }}"
    group: "{{ cf_app_pyapps_user }}"
    mode: 0755
    state: directory

- name: " Create the app folder"
  become_user: root
  become: yes
  file:
    dest: "/var/pyapps"
    owner: "{{ cf_app_pyapps_user }}"
    group: "{{ cf_app_pyapps_user }}"
    mode: 0755
    state: directory

- name: "Create Virtualenv"
  become_user: root
  become: yes
  shell: "cd /var/virtualenv ; /usr/local/bin/pyvenv-3.5 hhs_o_server "

- name: "Set ownership to pyapps"
  file:
    owner: "{{ cf_app_pyapps_user }}"
    group: "{{ cf_app_pyapps_user }}"
    dest: "/var/virtualenv"
    state: directory
    recurse: yes
