---
# File: refresh_app.yml 
# Created: 5/14/17
# Author: '@ekivemark'

- name: become root and activate virtualenv
  become: yes
  become_method: sudo
  become_user: root
  action: "shell source {{ venv }}/bin/activate"

- name: create app folder
  become_user: root
  become: yes
  file:
    dest: "{{ install_root }}/{{ project_name }}"
    state: directory
    owner: "{{ app_owner }}"
    group: "{{ app_group }}"
    mode:  "u+rw,g+rw,o-rwx"

- name: switch to app folder
  become_user: root
  become: yes
  shell: "cd {{ install_root }}/{{ project_name }} "

- name: "Check for git installation"
  stat:
    path: "{{ install_root }}/{{ project_name }}/.git/*"
  register: git_installed


- name: "Check result of git check"
  debug:
    msg: "git is [{{ git_installed }}]"

- name: "install from git: {{ project_repo }} branch:{{ git_branch }}"
  become_user: root
  become: yes
  git:
    repo: "{{ project_repo }}"
    dest: "{{ install_root }}/{{ project_name }}"
    force: yes
    clone: yes
  when: not git_installed.stat.exists

  # Now pull a specific branch
- name: "update from git: {{ project_repo }} branch:{{ git_branch }}"
  become_user: root
  become: yes
  git:
    repo: "{{ project_repo }}"
    dest: "{{ install_root }}/{{ project_name }}"
    version: "{{ git_branch }}"

# change ownership of files
- name: "Update file ownership"
  become_user: root
  become: yes
  file:
    path: "{{ install_root }}/{{ project_name }}/"
    recurse: yes
    owner: "{{ app_owner }}"
    group: "{{ app_group }}"
    mode:  "u+rw,g+rw,o-rwx"

# install dependencies with pip in virtualenv
- name: "pip install requirements"
  become_user: root
  become: yes
  pip:
    requirements: "{{ install_root }}/{{ project_name }}/requirements/requirements.txt"
    virtualenv: "{{ venv }}"

# Change ownership for libraries
- name: "Change ownership for libraries"
  become_user: root
  become: yes
  file:
    path: "{{ venv }}"
    recurse: yes
    owner: "{{ app_owner }}"
    group: "{{ app_group }}"
    mode:  "u+rw,g+rw,o-rwx"

- name: make manage.py executable
  become_user: root
  become: yes
  file:
    path: "{{ install_root }}/{{ project_name }}/manage.py"
    state: touch
    mode: "u+rwx,g+rwx,o-rwx"

- name: Django migrate
  become_user: root
  become: yes
  django_manage:
    command: migrate
    app_path: "{{ install_root }}/{{ project_name }}/"
    virtualenv: "{{ venv }}"
  when: migrate=yes

- name: Django collectstatic
  become_user: root
  become: yes
  django_manage:
    command: collectstatic
    app_path: "{{ install_root }}/{{ project_name }}/"
    virtualenv: "{{ venv }}"
  when: collectstatic=yes

- name: make sure apache server is running
  become_user: root
  become: yes
  service:
    name: httpd
    state: started
    enabled: yes

- name: Restart Apache
  become_user: root
  become: yes
  action: shell /bin/echo $HOSTNAME
  notify:
    - restart apache
