---
- name: Provision server
  hosts: all
  remote_user: ec2-user
  gather_facts: no
  vars:
    ansible_ssh_pipelining: no
    env: "dev"
    azone: "az1"
    sub_zone: "app"
    sg_zone: "appserver"
    env_az: "{{ env }}-{{ azone }}"
    splunk_target_layer: "app"
  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/env/{{ env }}/vault.yml"
    - "./../../vars/env/{{ env }}/env.yml"
    - "./../../vars/all_var.yml"

  roles:
    - ../../roles/base_patch
    - ../../roles/nessus_update_key
    - ../../roles/splunk

    - ../../roles/selinux # selinux_state
    - ../../roles/aws
    - ../../roles/app_tools
    - ../../roles/app_user
    - ../../roles/app_logs
    - ../../roles/python34
    - ../../roles/certstore # install_fhircerts_to_store
    # TODO(rnagle): this is not being used at the moment
    #- ../../roles/swagger_ui_install

    - ../../roles/app_prep
    - ../../roles/app_install
    - ../../roles/env_vars
    - ../../roles/new_relic
    - ../../roles/nginx

    - ../../roles/semanage_apps
    - ../../roles/semanage_virtualenv
