---
# File: /playbook/appherd/roles/copy_issued_cert/tasks/main.yml
# Created: 11/28/17
# Author: '@ekivemark'

# Copy the assigned certificate to appserver
# {{ apache_cert_store }} is typically set to  /etc/httpd/ssl/certs
# export CERT_STORE=/etc/httpd/ssl/certs

# based on: https://stackoverflow.com/questions/36182242/aws-elb-backend-server-over-https-with-self-signed-certificate


- name: "Copy Assigned Cert: Create {{ apache_cert_store }} "
  become_user: "{{ remote_admin_account }}"
  become: yes
  file:
    dest: "{{ apache_cert_store }}"
    mode: 0755
    owner: "root"
    group: "root"
    recurse: yes
    state: directory

- name: "copy certs from vault to {{ apache_cert_store }}"
  become_user: "{{ remote_admin_account }}"
  become: yes
  copy:
    content: "{{ item.content }}"
    dest: "{{ apache_cert_store }}/{{ item.name }}"
    mode: 0755
    owner: "root"
    group: "root"
  no_log: True
  with_items:
    - { "name": "cert.pem", "content": "{{ apache_cert_file }}" }
    - { "name": "key.pem", "content": "{{ apache_key_file }}" }
    - { "name": "fullchain.pem", "content": "{{ apache_fullchain_file }}" }

# apache_cert_file: "env_apache_cert_file" : "vault_env_apache_cert_file"
# apache_key_file: "env_apache_key_file" : "vault_env_apache_key_file"
# apache_fullchain_file: "env_apache_fullchain_file" : "vault_env_apache_fullchain_file"
