# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "bucket_name"
    dynamodb_table = "db_name"
    encrypt        = true
    key            = "path/terraform.tfstate"
    region         = "us-east-1"
  }
}
