---
# File: attach_ext_drive.yml 
# Created: 5/8/17
# Author: '@ekivemark'

# Use ansible commands to attach volume to /data
- name: "Attach ec2_vol to /data"
  mount:
    name: /data
    src: /dev/xvdb
    fstype: ext4
    state: mounted


#- name: "Create a script directory for root account"
#  become_user: root
#  file:
#    dest: /root/script
#    state: directory
#    owner: root
#    group: root
#
#- name: "Create External Drive script"
#  become_user: root
#  template:
#    src: "../templates/setup_ext_drive.j2"
#    dest: "/root/script/setup_ext_drive.sh"
#    backup: yes
#    owner: "root"
#    group: "root"
#    mode: "u+rwx"
#
#- name: "Execute External Drive Script"
#  become_user: root
#  shell: "/root/script/setup_ext_drive.sh"
#  register: external_drive_setup
