---
# File: playbook/appherd/roles/create_certstore/tasks/main.yml
# Created: 5/31/17
# Author: '@ekivemark'

# create a certificate store folder

- name: "Create a back-end app certstore"
  become_user: "{{ remote_admin_account }}"
  become: yes
  file:
    dest: "{{ cf_app_pyapp_home }}/certstore"
    mode: 0755
    owner: "{{ cf_app_pyapps_user }}"
    group: "{{ app_group }}"
    recurse: yes
    state: directory
