---
- name: Provision server
  hosts: all
  remote_user: ec2-user
  gather_facts: no
  vars:
    ansible_ssh_pipelining: no
#    env: "dev"
    azone: "az1"
    sub_zone: "app"
    sg_zone: "appserver"
#    env_az: "{{ env }}-{{ azone }}"
    splunk_target_layer: "app"
  vars_files:
    - "./../../vars/common.yml"
#    - "./../../vault/env/{{ env }}/vault.yml"
#    - "./../../vars/env/{{ env }}/env.yml"
    - "./../../vars/all_var.yml"

  roles:
  # TODO - this is not being used at the moment
  #- ../../roles/swagger_ui_install

    - ../../roles/base_patch
    - ../../roles/selinux # selinux_state
    - ../../roles/app_tools
    - ../../roles/python
    - ../../roles/nginx_uwsgi_install
    - ../../roles/cloudwatch_agent_base
