---
# File: main.yml 
# Created: 8/1/17
# Author: '@ekivemark'


- name: "create message directory"
  become_user: root
  become: yes
  file:
    dest: "/root/messages"
    owner: root
    group: root
    mode: 0600
    state: directory

# set sns_message_file if undefined
# This allows us to set the file name elsewhere and pass it
# to sns
- name: set message_file
  set_fact:
    sns_message_file: "/root/messages/sns_json.msg"
  when: sns_message_file is undefined

- name: set message subject
  set_fact:
    sns_subject: "{{ env|upper }}:{{ inventory_hostname }} "
  when: sns_subject is undefined

- name: set calling playbook
  set_fact:
    sns_playbook: "UNDEFINED: set *sns_playbook* in calling script"
  when: sns_playbook is undefined

- name: set calling playbook action
  set_fact:
    sns_playbook_action: "UNDEFINED: set *sns_playbook_action* in calling script"
  when: sns_playbook_action is undefined

- name: set the debug mode
  set_fact:
    sns_playbook_debug: false
  when: sns_playbook_debug is undefined

- name: "build sns message"
  become_user: root
  become: yes
  copy:
    content: |
      Environment: {{ env}}
      Playbook: {{sns_playbook }}
      Server: {{ inventory_hostname }}
      Action: {{ sns_playbook_action }}
      AWS User: {{ env_s3_bucket_account }}
      {% if sns_playbook_debug %}
      # ============================
      {{ hostvars| to_nice_json }}
      # ============================
      {% else %}
      Debug: *sns_playbook_debug* != true
      # ============================
      {% endif %}


    dest: "{{ sns_message_file }}"
    owner: root
    group: root
    mode: 0740


- name: "Prepare a notification message"
  become_user: root
  become: yes
  shell: |
    AWS_DEFAULT_PROFILE={{ s3_bucket_account }}
    AWS_DEFAULT_REGION={{ cf_region }}
    AWS_ACCESS_KEY_ID={{ aws_access_id }}
    AWS_SECRET_ACCESS_KEY={{ aws_secret_key }}
    /usr/local/bin/aws sns publish \
       --topic-arn {{ sns_topic_arn }} \
       --subject "{{ sns_subject }}" \
       --message file://{{ sns_message_file }}
  ignore_errors: yes

#
# topicARN=arn:aws:sns:us-east-1:501705132200:config-topic-BB

#
# /usr/local/bin/aws sns publish \
#    --topic-arn $topicARN \
#    --message "Deployment status is good" \
#    --subject "Test from $HOSTNAME."
