---
- name: "Set SSH pub key variable"
  set_fact: 
    "{{ item.name }}_ssh_key": "{{ item.public_key }}"
  loop: "{{ users | flatten(1) }}"

- name: "Add user"
  user:
    name: "{{ item.name }}"
    password: "{{ '!' | default(omit) }}"
    state: present
  loop: "{{ users | flatten(1) }}"
  become: true

- name: "Add user public key"
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ vars[item.name + '_ssh_key']}}"
    state: present
  loop: "{{ users | flatten(1) }}"
  become: true

- name: "Add user to sudoers file"
  lineinfile:
    path: /etc/sudoers
    state: present
    line: "{{ item.name }} ALL=(ALL) NOPASSWD: ALL"
    validate: /usr/sbin/visudo -cf %s
  loop: "{{ users | flatten(1) }}"
  become: true