---
- name: "Set SSH list"
  set_fact:
    users: "{{ users }}"
  loop: "{{ users }}"
- debug:
    var: users

- name: "Add user"
  user:
    name: "{{ item.name }}"
    password: "{{ '!' | default(omit) }}"
    state: present
  loop: "{{ users }}"
  become: true

- name: "Add user public key"
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.public_key }}"
    state: present
  loop: "{{ users }}"
  become: true

- name: "Add user to sudoers file"
  lineinfile:
    path: /etc/sudoers
    state: present
    line: "{{ item.name }} ALL=(ALL) NOPASSWD: ALL"
    validate: /usr/sbin/visudo -cf %s
  loop: "{{ users }}"
  become: true