---
# - name: "Set SSH pub key variable"
#   set_fact: 
#     "{{ item.name }}_ssh_key": "{{ item.public_key }}"
#   loop: "{{ lookup('users', 'all', wantlist=True) }}"

- name: "Add user"
  user:
    name: "{{ item.username }}"
    password: "{{ '!' | default(omit) }}"
    state: present
  when: item.username is defined
  become: true

- name: "Add user public key"
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.ssh_key }}"
    state: present
  when: item.ssh_key is defined
  become: true

- name: "Add user to sudoers file"
  lineinfile:
    path: /etc/sudoers
    state: present
    line: "{{ item.username }} ALL=(ALL) NOPASSWD: ALL"
    validate: /usr/sbin/visudo -cf %s
  when: item.username is defined
  become: true