---

- name: "Create a List for SSH Users"
  set_fact:
    ssh_users:  [ { "{{ lookup('aws_ssm', '/bb2/test/app/ssh_don_seymour', region='us-east-1') }}" }, 
                  { "{{ lookup('aws_ssm', '/bb2/test/app/ssh_david_tisza', region='us-east-1') }}" }, 
                  { "{{ lookup('aws_ssm', '/bb2/test/app/ssh_nicholas_bragdon', region='us-east-1') }} " }, 
                  { "{{ lookup('aws_ssm', '/bb2/test/app/ssh_james_fuqian', region='us-east-1') }}" }
                ]

- name: "Print the ssh_user records after getting from aws_ssm"
  debug: 
    msg: "{{ ssh_users }}"

- name: "Add user"
  user:
    name: "{{ item.username }}"
    password: "{{ item.password | default(omit) }}"
    state: present
  with_items: "{{ ssh_users }}"
  become: true

- name: "Add user public key"
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.public_key }}"
    state: present
  when: item.public_key is defined
  with_items: "{{ ssh_users }}"
  become: true

- name: "Add user to sudoers file"
  lineinfile:
    path: /etc/sudoers
    state: present
    line: "{{ item.username }} ALL=(ALL) NOPASSWD: ALL"
    validate: /usr/sbin/visudo -cf %s
  when: item.sudoer == "true"
  with_items: "{{ ssh_users }}"
  become: true