---
- name: Apply security patches
  become_user: "{{ remote_admin_account }}"
  become: yes
  command: "dnf upgrade --security --sec-severity Critical --sec-severity Important -y"
  
- name: "Create .aws directory"
  become_user: "{{ remote_admin_account }}"
  become: yes
  file:
    dest: /root/.aws
    mode: 0600
    owner: root
    group: root
    state: directory

- name: "Write aws config file"
  become_user: "{{ remote_admin_account }}"
  become: yes
  template:
    src: "../templates/root_aws_config.j2"
    dest: "/root/.aws/config"
    backup: yes
    owner: root
    group: root
    mode: "u+r"
- name: Ensure SSM Agent is running
  become: true
  systemd:
    name: amazon-ssm-agent
    enabled: yes
    state: started

- name: Install Session Manager Plugin on AL2023
  become_user: "{{ remote_admin_account }}"
  become: yes
  shell: |
    curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux64/session-manager-plugin.rpm" -o "session-manager-plugin.rpm"
    dnf install -y ./session-manager-plugin.rpm
    rm -f session-manager-plugin.rpm
  args:
    executable: /bin/bash
