---
# File: shell_attach_vol.yml 
# Created: 5/8/17
# Author: '@ekivemark'

- name: "Create a script directory for root account"
  file:
    dest: "/home/ec2-user/script"
    state: directory
    mode: 0755

- name: setup volume 1
  set_fact:
    app_extra_volume: "{{ app_extra_volume_1 }}"

- name: "Create External Drive script"
  template:
    src: "../templates/setup_ext_drive.sh.j2"
    dest: "/home/ec2-user/script/setup_ext_drive.sh"
    backup: yes
    mode: "u+rwx"

- name: "Execute External Drive Script"
  become_user: root
  become: yes
  shell: "/home/ec2-user/script/setup_ext_drive.sh"
  register: external_drive_setup

- name: "save results for volume 1"
  set_fact:
    app_external_drive1:
      - "{{ external_drive_setup }}"

- name: setup volume 2
  set_fact:
    app_extra_volume: "{{ app_extra_volume_2 }}"

- name: "Create External Drive script"
  template:
    src: "../templates/setup_ext_drive.sh.j2"
    dest: "/home/ec2-user/script/setup_ext_drive.sh"
    backup: yes
    mode: "u+rwx"

- name: "Execute External Drive Script"
  become_user: root
  become: yes
  shell: "/home/ec2-user/script/setup_ext_drive.sh"
  register: external_drive_setup

- name: "save results for volume 2"
  set_fact:
    app_external_drive2:
      - "{{ external_drive_setup }}"

- name: "save results for both volumes"
  set_fact:
    app_external_drives:
      - "{{ app_external_drive1 }}"
      - "{{ app_external_drive2 }}"

- name: "migrate /tmp"
  become_user: root
  become: yes
  shell: |
    cd /tmp
    cp -ax * /tmp2
    cd /
    mv tmp tmp.old
    mkdir tmp
    umount /dev/xvdf
    mount /dev/xvdf /tmp
    grep -v "/tmp2 " /etc/fstab > /etc/fstab.new1
    echo /dev/xvdf       /tmp     ext4    defaults    0 0 >> /etc/fstab.new1
  register: app_external_drive_move_1


- name: "migrate /var"
  become_user: root
  become: yes
  shell: |
    cd /var
    cp -ax * /var2
    cd /
    mv var var.old
    mkdir var
    umount /dev/xvdg
    mount /dev/xvdg /var
    grep -v "/var2 " /etc/fstab.new1 > /etc/fstab.new2
    echo /dev/xvdg       /var     ext4    defaults    0 0 >> /etc/fstab.new2

  register: app_external_drive_move_2


