---
- name: "Creating Appserver User"
  become_user: "{{ remote_admin_account }}"
  become: yes
  user:
    name: "{{ app_pyapps_user }}"
#    password: "{{ cf_app_pyapps_pwd | password_hash('sha512') }}"
