---
#  loadtest playbook:
#  
#  Tasks performed:
#  1. Install docker and git on the ephemeral ec2 host.
#  2. Clone the web-deployment repo
#  3. Run the load test rig and capture the output/results to a log file
#  4. Transfer the output to an S3 bucket for retreival later.
#  

- name: Running LOADTEST playbook
  hosts: run_servers
  remote_user: ec2-user
  gather_facts: yes
  vars:
    ansible_ssh_pipelining: no
    results_fn: "{{ lookup('pipe', 'date +%Y%m%d%H%M') }}_loadtest_results.log"
    src_results_file: "/home/ec2-user/bluebutton-web-deployment/locust/{{ results_fn }}"
    dst_results_file: "{{ env }}/{{ results_fn }}"
    aws_access_key: "{{ hostvars['localhost'] }}"

  environment:
    BB_CLIENT_ID: "{{ PB_CLIENT_ID }}"
    BB_CLIENT_SECRET: "{{ PB_CLIENT_SECRET }}"
    BB_SUB_DOMAIN: "{{ PB_SUB_DOMAIN }}"
    BB_LOAD_TEST_TYPE: "{{ PB_LOAD_TEST_TYPE }}"
    BB_NUM_BENES: "{{ PB_NUM_BENES }}"
    BB_TKNS_WORKERS: "{{ PB_TKNS_WORKERS }}"
    BB_LOAD_TEST_DURATION: "{{ PB_LOAD_TEST_DURATION }}"
    BB_LOAD_TEST_HATCH_RATE: "{{ PB_LOAD_TEST_HATCH_RATE }}"
    BB_LOAD_TEST_MIN_WAIT: "{{ PB_LOAD_TEST_MIN_WAIT }}"
    BB_LOAD_TEST_MAX_WAIT: "{{ PB_LOAD_TEST_MAX_WAIT }}"

  tasks:
    - name: "Install git and docker deps and boto3"
      become: yes
      yum:
        name: "{{ item }}"
        state: present
      with_items:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - git
      - python-boto
      - python2-boto
      - python2-boto3

    - name: Add docker-ce repository
      become: yes
      shell: |
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        exit 0
      register: command_result
    - debug: msg="{{ command_result.stdout_lines }}"

    - name: Enable rhui-REGION-rhel-server-extras repository
      become: yes
      shell: |
        yum-config-manager --enable rhui-REGION-rhel-server-extras
        exit 0
      register: command_result
    - debug: msg="{{ command_result.stdout_lines }}"

    - name: "Install docker-ce"
      become: yes
      yum:
        name: "docker-ce"
        state: present

    - name: "Start docker service"
      become: yes
      service:
        name: docker
        state: restarted
        enabled: yes

    - name: "Add ec2-user to docker group"
      become: yes
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: "GIT | install from : {{ PB_GIT_URL }} branch:{{ PB_BRANCH }}"
      git:
        repo: "{{ PB_GIT_URL }}"
        dest: "bluebutton-web-deployment"
        version: "{{ PB_BRANCH }}"
        force: yes
        clone: yes

    - name: "Run loadtest software and log results"
      shell: |
        cd bluebutton-web-deployment/locust
        date
        echo "Loadtest variables:"
        env | grep BB_
        echo
        echo
        fn="{{ results_fn }}"
        ./run.sh ${BB_LOAD_TEST_TYPE} >${fn} 2>&1
        date
        tail -n 50 ${fn}
        exit 0
      register: command_result
      ignore_errors: yes
    - debug: msg="{{ command_result.stdout_lines }}"

    - name: "Put results file to AWS S3 bucket: {{ PB_AWS_S3_BUCKET }} src: {{ src_results_file }}  dst: {{ dst_results_file }}"
      aws_s3:
        bucket: "{{ PB_AWS_S3_BUCKET }}"
        object: "{{ dst_results_file }}"
        src: "{{ src_results_file }}"
        mode: put
      ignore_errors: yes
