---
# File: playbook/appserver/roles/app_logs/tasks/main.yml
# Created: 5/15/17
# Author: '@ekivemark'
# setup application logging

# Create the App logging directory and touch the app logs
# Set SELinux permissions

- name: "Create the app log directory "
  become_user: "{{ remote_admin_account }}"
  become: yes
  file:
    dest: "{{ cf_app_log_dir }}"
    owner: root
    group: logreader
    state: directory
    mode: 0775

# Logs need to be given group ownership to logreader
- name: "Create the logs"
  become_user: "{{ remote_admin_account }}"
  become: yes
  file:
    dest: "{{ cf_app_log_dir }}/{{ item }}"
    owner: "{{ cf_app_pyapps_user }}"
    group: logreader
    state: touch
    mode: 0776
  with_items:
    - debug.log
    - error.log
    - info.log
    - perf_mon.log
    - export.log

- name: "Set permissions for SELinux"
  become_user: "{{ remote_admin_account }}"
  become: yes
  shell: "semanage fcontext -a -t httpd_sys_content_t \"{{ cf_app_log_dir }}(/.*)?\" "
  ignore_errors: yes


#- name: "Create the error log"
#  become_user: "{{ remote_admin_account }}"
#  become: yes
#  file:
#    dest: "{{ cf_app_log_dir }}/error.log"
#    owner: "{{ cf_app_pyapps_user }}"
#    group: logreader
#    state: touch
#    mode: 0766
#
#- name: "Create the info log"
#  become_user: "{{ remote_admin_account }}"
#  become: yes
#  file:
#    dest: "{{ cf_app_log_dir }}/info.log"
#    owner: "{{ cf_app_pyapps_user }}"
#    group: logreader
#    state: touch
#    mode: 0766


