---
# File: playbook/appherd/fix_permissions/tasks/main.yml
# Created: 3/15/18
# Author: '@ekivemark'


- name: Django fix permissions for admin
  become_user: "{{ remote_admin_account }}"
  become: yes
  run_once: yes
  django_manage:
    command: fix_permissions
    app_path: "{{ install_root }}/{{ project_name }}/"
    virtualenv: "{{ venv }}"

