---
# File: playbook/appserver/roles/django_prep/tasks/main.yml
# Created: 5/26/17
# Author: '@ekivemark'

# Perform django migrate and django collectstatic
# add in group create for first run only.

- name: Django migrate
  become_user: root
  become: yes
  django_manage:
    command: migrate
    app_path: "{{ install_root }}/{{ project_name }}/"
    virtualenv: "{{ venv }}"
  when: "( {{ migrate | default('yes') }} == 'yes' )"

- name: "Add Group roles to database"
  become_user: root
  become: yes
  django_manage:
    command: loaddata apps/accounts/fixtures/groups.json
    app_path: "{{ install_root }}/{{ project_name }}/"
    virtualenv: "{{ venv }}"
  when: "( {{ add_groups | default('no') }} == 'yes' )"

- name: "Add Scopes to database"
  become_user: root
  become: yes
  django_manage:
    command: loaddata apps/accounts/fixtures/scopes.json
    app_path: "{{ install_root }}/{{ project_name }}/"
    virtualenv: "{{ venv }}"
  when: "( {{ add_scopes | default('no') }} == 'yes' )"

- name: Django collectstatic
  become_user: root
  become: yes
  django_manage:
    command: collectstatic
    app_path: "{{ install_root }}/{{ project_name }}/"
    virtualenv: "{{ venv }}"
  when: "( {{ collectstatic | default('yes') }} == 'yes' )"

