---
# File: roles/add_authorized_keys/tasks/main.yml
# Created: 12/5/17
# Author: '@ekivemark'

# Get authorized keys from vault and add to .ssh/authorized_keys for user

# future enhancement will be to pass in user and keys as variables.

- name: "setting authorized_keys for user: {{ ssh_user }}"
  become_user: "{{ remote_admin_account }}"
  become: yes
  authorized_key:
    user: "{{ ssh_user }}"
    state: present
    exclusive: "{{ ssh_key_replace }}"
    key: "{{ ssh_auth_keys }}"

