---
# File: playbook/dataserver/roles/alter_user/tasks/umain.yml
# Created: 5/31/17
# Author: '@ekivemark'

# Update app user in database

- name: "update app user account"
  become_user: root
  become: yes
  template:
    src: "../templates/db_alter_user_script.j2"
    dest: "{{ db_server_data_dir }}/django_alter_user.sql"
    backup: yes
    owner: "{{ db_server_account }}"
    group: "{{ db_server_account }}"
    mode: "u+rwx"

- name: "Run alter_user sql script"
  become_user: "{{ db_server_account}}"
  become: yes
  shell: "psql -p {{ db_host_port }} -f {{ db_server_data_dir }}/django_alter_user.sql"
  register: django_alter_user

