---
# File: /roles/fips140_off/tasks/main.yml
# Created: 11/29/17
# Author: '@ekivemark'

# based on: https://access.redhat.com/solutions/2422061

# yum remove dracut-fips\*
# mv -v /boot/initramfs-$(uname -r).img{,.FIPS-bak}
# dracut
# grubby --update-kernel=ALL --remove-args=fips=1
# [[ -f /etc/default/grub ]] && sed -i 's/ fips=1//' /etc/default/grub
# reboot
# sysctl crypto.fips_enabled

- name: "FIPS enabled: Off"
  become_user: root
  become: yes
  yum:
    name: dracut-fips\*
    state: absent

- name: "backup boot file (intramfs)"
  become_user: root
  become: yes
  command: "mv -v /boot/initramfs-$(uname -r).img{,.FIPS-bak}"

- name: "rebuild intramfs"
  become_user: root
  become: yes
  command: "dracut"

- name: "remove fips=1 from kernel command line"
  become_user: root
  become: yes
  shell: |
    grubby --update-kernel=ALL --remove-args=fips=1
    [[ -f /etc/default/grub ]] && sed -i 's/ fips=1//' /etc/default/grub

- name: Reboot the machine
  become_user: root
  become: yes
  shell: nohup bash -c "sleep 2s && reboot" &

- name: Wait for machine to come back
  become_user: root
  become: yes
  wait_for_connection:
    timeout: 120

