---
- name: "install base app server components"
  remote_user: ec2-user
  become_user: "{{ remote_admin_account }}"
  become: yes
  yum:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - gcc
    - git
    - postgresql-devel
    - python-devel

- name: "install pip 9.0.3"
  become_user: "{{ remote_admin_account }}"
  become: yes
  shell: easy_install pip==9.0.3

- name: "install newer version of awscli - needed for elbv2"
  become_user: "{{ remote_admin_account }}"
  become: yes
  shell: pip install --upgrade awscli
