---
# File: roles/python3/tasks/main.yml
# Created: 5/10/17
# Author: '@ekivemark'
# download and install python3

- name: "create download directory"
  file:
    dest: "/home/ec2-user/download"
    state: directory
    mode: 0600
    owner: "ec2-user"
    group: "ec2-user"
  register: app_download_dir

- name: "Download python {{ python_ver_full }}"
  become_user: root
  become: yes
  unarchive:
    src: "https://www.python.org/ftp/python/{{ python_ver_full }}/Python-{{ python_ver_full }}.tar.xz"
    dest: "/home/ec2-user/download"
    remote_src: True

- name: "Running ./configure for Python {{ python_ver_full }}"
  become_user: root
  become: yes
  command: "cd /home/ec2-user/download/Python-{{ python_ver_full }} ; ./configure --prefix=/usr/local --enable-shared  LDFLAGS='-Wl,-rpath /usr/local/lib' --enable-optimizations "

- name: "Running make for Python {{ python_ver_full }}"
  become_user: root
  become: yes
  command: "cd /home/ec2-user/download/Python-{{ python_ver_full }} ; make "

- name: "Running make test for Python {{ python_ver_full }}"
  become_user: root
  become: yes
  command: "cd /home/ec2-user/download/Python-{{ python_ver_full }} ; make test "

- name: "Running make altinstall for Python {{ python_ver_full }}"
  become_user: root
  become: yes
  command: "cd /home/ec2-user/download/Python-{{ python_ver_full }} ; make altinstall "
  register: py3_output

