---
# File: roles/python3/tasks/main.yml
# Created: 5/10/17
# Author: '@ekivemark'
# download and install python3

- name: "create download directory"
  file:
    dest: "/home/ec2-user/download"
    state: directory
    mode: 0600
    owner: "ec2-user"
    group: "ec2-user"
  register: app_download_dir

- name: "Download python {{ python_ver_full }}"
  become_user: root
  become: yes
  unarchive:
    src: "https://www.python.org/ftp/python/{{ python_ver_full }}/Python-{{ python_ver_full }}.tar.xz"
    dest: "/home/ec2-user/download"
    remote_src: True

- name: "Running ./configure for Python {{ python_ver_full }}"
  become_user: root
  become: yes
  command: "cd /home/ec2-user/download/Python-{{ python_ver_full }} ; ./configure --prefix=/usr/local --enable-shared  LDFLAGS='-Wl,-rpath /usr/local/lib' --enable-optimizations "

- name: "Running make for Python {{ python_ver_full }}"
  become_user: root
  become: yes
  command: "cd /home/ec2-user/download/Python-{{ python_ver_full }} ; make "

- name: "Running make altinstall for Python {{ python_ver_full }}"
  become_user: root
  become: yes
  command: "cd /home/ec2-user/download/Python-{{ python_ver_full }} ; make altinstall"

- name: "Download mod_wsgi_{{ mod_wsgi_ver_full }}"
  become_user: root
  become: yes
  get_url:
    url: "https://codeload.github.com/GrahamDumpleton/mod_wsgi/tar.gz/{{ mod_wsgi_ver_full }}"
    dest: "/home/ec2-user/download/mod_wsgi_{{ mod_wsgi_ver_full }}.tar.gz"
    remote_src: True

- name: "Unarchive mod_wsgi_{{ mod_wsgi_ver_full }}"
  become_user: root
  become: yes
  shell: "cd /home/ec2-user/download ; /usr/bin/tar -xzvf /home/ec2-user/download/mod_wsgi_{{ mod_wsgi_ver_full }}.tar.gz ; cd /home/ec2-user/download/mod_wsgi-{{ mod_wsgi_ver_full }} "
  register: mod_wsgi_info

- name: "Running configure for mod_wsgi"
  become_user: root
  become: yes
  command: "cd /home/ec2-user/download/mod_wsgi-{{ mod_wsgi_ver_full }} ; ./configure --with-python=/usr/local/bin/python{{ python_ver }} --with-apxs=/usr/bin/apxs "

- name: "Prepare to refresh ld cache"
  become_user: root
  become: yes
  lineinfile:
    dest: "/etc/ld.so.conf"
    line: "/usr/local/lib"
    state: present

- name: "Refresh LD Cache"
  become_user: root
  become: yes
  command: "/sbin/ldconfig"

- name: "Running make for mod_wsgi"
  become_user: root
  become: yes
  command: "cd /home/ec2-user/download/mod_wsgi-{{ mod_wsgi_ver_full }} ; make "

- name: "Running make install for mod_wsgi"
  become_user: root
  become: yes
  command: "cd /home/ec2-user/download/mod_wsgi-{{ mod_wsgi_ver_full }} ; make install "



