---
# File: playbook/appserver/roles/app_update_env/tasks/main.yml
# Created: 5/15/17
# Author: '@ekivemark'

# Write the environment variable files

- name: "Write custom-envvars file"
  become_user: root
  become: yes
  template:
    src: ../templates/custom-envvars.j2
    dest: "{{ install_root }}/custom-envvars.py"
    backup: yes
    owner: "{{ app_owner }}"
    group: "{{ app_group }}"
    mode: 0664

- name: "write django_settings.sh script"
  become_user: root
  become: yes
  template:
    src: ../templates/django_settings.j2
    dest: "{{ install_root }}/django_settings.sh"
    backup: yes
    owner: "{{ app_owner }}"
    group: "{{ app_group }}"
    mode: 0664


- name: "Make new files executable"
  become_user: root
  become: yes
  shell: "chmod +x {{ cf_app_pyapp_home }}"

