---
- name: Provision server
  hosts: all
  remote_user: ec2-user
  gather_facts: no
  vars:
    ansible_ssh_pipelining: no
    azone: "az1"
    sub_zone: "app"
    sg_zone: "appserver"
    splunk_target_layer: "app"
    users:
      - name: "don_seymour"
        public_key: "{{ lookup('aws_secret', '/bb2/allenv/app/ssh_user_don_seymour', region='us-east-1') }}"
      - name: "david_tisza"
        public_key: "{{ lookup('aws_secret', '/bb2/allenv/app/ssh_user_david_tisza', region='us-east-1') }}"
      - name: "adrian_jones"
        public_key: "{{ lookup('aws_secret', '/bb2/allenv/app/ssh_user_adrian_jones', region='us-east-1') }}"
  vars_files:
    - "./../../vars/common.yml"
    - "./../../vars/env/shared/env.yml"
    - "./../../vars/all_var.yml"
  roles:
    - ../../roles/amzn2_base
    - ../../roles/cloudwatch_agent_base
    - ../../roles/ssh_users