---
- name: Provision server
  hosts: all
  remote_user: ec2-user
  gather_facts: no
  vars:
    ansible_ssh_pipelining: no
    azone: "az1"
    sub_zone: "app"
    sg_zone: "appserver"
    splunk_target_layer: "app"
    ssh_group:
      - "{{ lookup('aws_ssm', '/bb2/allenv/app/ssh_user_ds', region='us-east-1') }}"
      - "{{ lookup('aws_ssm', '/bb2/allenv/app/ssh_user_dt', region='us-east-1') }}"
      - "{{ lookup('aws_ssm', '/bb2/allenv/app/ssh_user_jf', region='us-east-1') }}"
      - "{{ lookup('aws_ssm', '/bb2/allenv/app/ssh_user_aj', region='us-east-1') }}"
  vars_files:
    - "./../../vars/common.yml"
    - "./../../vars/env/shared/env.yml"
    - "./../../vars/all_var.yml"
  roles:
    - ../../roles/amzn2_base
    - ../../roles/cloudwatch_agent_base
    - ../../roles/ssh_users