---
- name: Provision server
  hosts: all
  remote_user: ec2-user
  gather_facts: no
  users:
    - name: don.seymour
      param_store_path: /bb2/allenv/app/ssh_user_don_seymour
    - name: david.tisza
      param_store_path: /bb2/allenv/app/ssh_user_david_tisza
    - name: james.fuqian
      param_store_path: /bb2/allenv/app/ssh_user_james_fuqian
    - name: adrian.jones
      param_store_path: /bb2/allenv/app/ssh_user_adrian_jones
  vars:
    ansible_ssh_pipelining: no
    azone: "az1"
    sub_zone: "app"
    sg_zone: "appserver"
    splunk_target_layer: "app"
    # ssh_group:
    #   - ds: "{{ lookup('aws_ssm', '/bb2/allenv/app/ssh_user_ds', region='us-east-1') }}"
    #   - dt: "{{ lookup('aws_ssm', '/bb2/allenv/app/ssh_user_dt', region='us-east-1') }}"
    #   - jf: "{{ lookup('aws_ssm', '/bb2/allenv/app/ssh_user_jf', region='us-east-1') }}"
    #   - aj: "{{ lookup('aws_ssm', '/bb2/allenv/app/ssh_user_aj', region='us-east-1') }}"
  vars_files:
    - "./../../vars/common.yml"
    - "./../../vars/env/shared/env.yml"
    - "./../../vars/all_var.yml"
  roles:
    - ../../roles/amzn2_base
    - ../../roles/cloudwatch_agent_base
    - ../../roles/ssh_users