---
- name: Provision server
  hosts: all
  remote_user: ec2-user
  gather_facts: no
  vars:
    ansible_ssh_pipelining: no
    azone: "az1"
    sub_zone: "app"
    sg_zone: "appserver"
    splunk_target_layer: "app"
    users:
      - username: "melissa_guzman"
        ssh_key: "{{ lookup('aws_secret', '/bb2/allenv/app/ssh_user_melissa_guzman', region='us-east-1') }}"
      - username: "jimmy_fagan"
        ssh_key: "{{ lookup('aws_secret', '/bb2/allenv/app/ssh_user_jimmy_fagan', region='us-east-1') }}"
      - username: "logan_bertram"
        ssh_key: "{{ lookup('aws_secret', '/bb2/allenv/app/ssh_user_logan_bertram', region='us-east-1') }}"
      - username: "jim_fuqian"
        ssh_key: "{{ lookup('aws_secret', '/bb2/allenv/app/ssh_user_jim_fuqian', region='us-east-1') }}"
      - username: "vaishali_cholkar"
        ssh_key: "{{ lookup('aws_secret', '/bb2/allenv/app/ssh_user_vaishali_cholkar', region='us-east-1') }}"
      - username: "shivam_tiwari"
        ssh_key: "{{ lookup('aws_secret', '/bb2/allenv/app/ssh_user_shivam_tiwari', region='us-east-1') }}"
      - username: "noor_shaik"
        ssh_key: "{{ lookup('aws_secret', '/bb2/allenv/app/ssh_user_noor_shaik', region='us-east-1') }}"
  vars_files:
    - "./../../vars/common.yml"
    - "./../../vars/env/shared/env.yml"
    - "./../../vars/all_var.yml"
  roles:
    - ../../roles/amzn2_base
    - ../../roles/cloudwatch_agent_base
    - ../../roles/ssh_users
