---
# File: yum update.yml 
# Created: 5/17/17
# Author: '@ekivemark'
# Apply yum updates to all machines

- name: "Applying patches"
  hosts: "{{ build_target }}"
  # hosts: appservers
  # connection: local
  remote_user: ec2-user
  become_user: root
  become: yes
  gather_facts: True
  vars:
    ansible_ssh_pipelining: no
    env: "dev"
    env_cf_app_version: "01"

  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/env/{{ env }}/vault.yml"
    - "./../../vars/env/{{ env }}/env.yml"
    - "./../../vars/all_var.yml"

  tasks:
  - include: "./roles/ntp_update/tasks/main.yml"
