---
# File: platform.yml
# Created: 4/21/17
- name: Platform creation
  hosts: localhost
  remote_user: root
  connection: local
  # gather_facts: False
  vars:
    env: "dev"
  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/env/{{ env }}/vault.yml"
    - "./../../vars/env/{{ env }}/env.yml"
    - "./../../vars/all_var.yml"

# and this is how we include another playbook, be careful and
# don't recurse infinitely or anything.  Note you can't use
# any variables in the include path here.

- import_tasks: ../dataserver/create_database.yml



- import_tasks: ../appserver/create_appserver.yml

