---
# File: platform.yml
# Created: 4/21/17
- name: Platform creation
  hosts: localhost
  remote_user: root
  connection: local
  # gather_facts: False
  vars:
    env: "dev"
  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/env/{{ env }}/vault.yml"
    - "./../../vars/env/{{ env }}/env.yml"
    - "./../../vars/all_var.yml"

- import_tasks: ../appserver/create_appserver.yml
