---
# File: playbook/platform/rewrite_hosts.yml
# Created: 5/17/17
# Author: '@ekivemark'

# Re-write the hosts file
# Run this after building a dataserver or appserver
# Assumptions:
#   - ec2 instance has the following tags:
#         -- "tag:Environment": "{{ env|upper }}"
#         -- "tag:Managed": "BB-MANAGED-{{ env|upper }}"

- name: "Rewrite Ansible hosts file"
  hosts: localhost
  connection: local
  remote_user: ec2-user
  # become_user: root
  # become: yes
  gather_facts: True
  vars:
    ansible_ssh_pipelining: no
    env: "dev"
    azone: "az1"
    sub_zone: "app"
    sg_zone: "appserver"
    env_az: "{{ env }}-{{ azone }}"
    env_cf_app_version: "01"
    splunk_client_name: "BBAPI-{{ env|upper }}-{{ sub_zone|upper }}"
  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/env/{{ env }}/vault.yml"
    - "./../../vars/env/{{ env }}/env.yml"
    - "./../../vars/all_var.yml"

  tasks:
  - name: get aws_region
    set_fact:
        aws_region: "{{ lookup('ini', 'region section=default file=/root/.aws/config') }}"
  - debug:
      msg: "using default region {{ aws_region }} "

  - name: get aws_key
    set_fact:
        aws_access_id: "{{ lookup('ini', 'aws_access_key_id section=default file=/root/.aws/credentials') }}"
  - debug:
      msg: "using default access key {{ aws_access_id }} "

  - name: get aws_secret
    set_fact:
        aws_secret_key_id: "{{ lookup('ini', 'aws_secret_access_key section=default file=/root/.aws/credentials') }}"
  - debug:
      msg: "using default secret {{ aws_secret_key_id }} "

  - name: "Get remote facts for vpc {{ cf_vpc_id }}"
    ec2_remote_facts:
      aws_access_key: "{{ aws_access_id }}"
      aws_secret_key: "{{ aws_secret_key_id }}"
      region: "{{ aws_region }}"
      filters:
        vpc_id: "{{ cf_vpc_id }}"
        "tag:Environment": "{{ env|upper }}"
        "tag:Managed": "BB-MANAGED-{{ env|upper }}"
    register: ec2_remote_facts_info

  - name: "write hosts file"
    connection: local
    template:
      src: ../../templates/environment/ansible_hosts.j2
      dest: /etc/ansible/hosts



