---
# File: playbook/platform/snmp_update.yml
# Created: 12/1/17
# Author: '@ekivemark'
# change snmp community string from default of public

- name: "change snmp community string from public to"
  hosts: "{{ build_target }}"
  # hosts: appservers
  # connection: local
  remote_user: ec2-user
  become_user: "{{ remote_admin_account }}"
  become: yes
  gather_facts: True
  vars:
    ansible_ssh_pipelining: no
    env: "test"
    env_cf_app_version: "01"
    snmp_community_string: "oedabluebuttonsnmpcommunity"

  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/env/{{ env }}/vault.yml"
    - "./../../vars/env/{{ env }}/env.yml"
    - "./../../vars/all_var.yml"

  tasks:
  - import_tasks: "./../roles/snmp_update_public/tasks/main.yml"