---
# File: update_nagios.yml 
# Created: 6/8/17
# Author: '@ekivemark'

# Patch for nagios (RHSA­2017:0259)

# update the nagios package
# Scope: All Environment Servers
# Purpose: Default nagios package has a security vulnerability.
# This playbook applies the approved package to remediate the vulnerability.

- hosts: "{{ build_target }}"
  vars:
    env: "dev"
    ansible_ssh_pipelining: no

  # env value is passed in from command line using
  #   --extra-vars env=dev | test | impl | prod
  # Vars file is relative to playbook file
  # Sequence:
  # 1. Common variables
  # 2. encrypted vault file
  # 3. environment specific variables
  # 4. all_vars which reference the preceding three files.
  # common_ prefixes common variables
  # vault_env_ prefixes encrypted variables
  # env_ prefixes environment specific variables
  # all_var incorporates preceding variables and defines variables without prefixes.
  # use all_var variables in scripts.
  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/env/{{ env }}/vault.yml"
    - "./../../vars/env/{{ env }}/env.yml"
    - "./../../vars/all_var.yml"
    # - ../vars/all_vars.yml
    # - ../../vars/playbook/template_envvars.yml

  remote_user: "{{ remote_user_account }}"
  become: yes
  become_user: "{{ mon_nessus_user }}"

  tasks:
  - include: roles/nagios_update/tasks/main.yml