---
# File: playbook/security/roles/postgres_upgrade/tasks/main.yml
# Created: 12/20/17
# Author: '@ekivemark'


- name: "Upgrade postgresql"
  remote_user: ec2-user
  become_user: "{{ remote_admin_account }}"
  become: yes
  yum:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - postgresql


- name: Get installed packages
  become_user: "{{ remote_admin_account }}"
  become: yes
  yum:
    list: installed
  register: yum_packages
  changed_when: False

- name: "View the contents of yum_packages"
  debug:
    var: yum_packages

- name: "check postgres"
  debug:
    msg: item
  with_items: "{{yum_packages|json_query(jsonquery)}}"
  vars:
    jsonquery: "results[?name=='postgresql'].version"