---
# File: playbook/appserver/install_cert.yml
# Created: 5/31/17
# Author: '@ekivemark'

# install a private key to the appserver

# Based on: http://odecee.com.au/cloudformation-and-ansible/
# Vars file is relative to playbook file
# vars_files:
# Vars file is relative to playbook file
# Sequence:
# 1. Common variables
# 2. encrypted vault file
# 3. environment specific variables
# 4. all_vars which reference the preceding three files.
# common_ prefixes common variables
# vault_env_ prefixes encrypted variables
# env_ prefixes environment specific variables
# all_var incorporates preceding variables and defines variables without prefixes.
# use all_var variables in scripts.

- name: "Install Back-end client certificate"
  # hosts: appservers
  hosts: "{{ build_target }}"
  # connection: local
  remote_user: ec2-user
  become_user: root
  become: yes
  gather_facts: True
  vars:
    ansible_ssh_pipelining: no
    env: "dev"
    sub_zone: "app"
    # use extra-vars to define:
    # local directory containing key and cert pair
    src_cert_dir: ''
    # target sub-dir under certstore/
    # to avoid key conflicts
    cert_sub_dir: ''
    # source certificate.pem file - name will be retained on target
    src_cert: ''
    # source key.pem file - name will be retained on target
    src_key: ''

  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/env/{{ env }}/vault.yml"
    - "./../../vars/env/{{ env }}/env.yml"
    - "./../../vars/all_var.yml"



  tasks:
  - include: roles/create_certstore/tasks/main.yml

  - name: "Add {{ cert_sub_dir }} to certstore"
    file:
      dest: "{{ cf_app_pyapp_home }}/certstore/{{ cert_sub_dir }}"
      mode: 0755
      owner: "{{ cf_app_pyapps_user }}"
      group: "{{ app_group }}"
      recurse: yes
      state: directory

  - name: "copy cert({{ src_cert }}) to certstore [{{ cert_sub_dir }}]"
    copy:
      src: "{{ src_cert_dir }}/{{ src_cert }}"
      dest: "{{ cf_app_pyapp_home }}/certstore/{{ cert_sub_dir }}/{{ src_cert }}"
      mode: 0755
      owner: "{{ cf_app_pyapps_user }}"
      group: "{{ app_group }}"
    when: "src_cert_dir != '' and src_cert != '' "

  - name: "copy key({{ src_key }}) to certstore [{{ cert_sub_dir }}]"
    copy:
      src: "{{ src_cert_dir }}/{{ src_key }}"
      dest: "{{ cf_app_pyapp_home }}/certstore/{{ cert_sub_dir }}/{{ src_key }}"
      mode: 0755
      owner: "{{ cf_app_pyapps_user }}"
      group: "{{ app_group }}"
    when: "src_cert_dir != '' and src_key != '' "



    # mkdir -p /var/pyapps/certs/bb-sandbox
    #cd /
    #unzip /home/ec2-user/download/certs.zip
    #cp /home/ec2-user/download/certs/* /var/pyapps/cets/bb-sandbox/
    #
    ##cp /root/ca/certs/ca.cert* /var/pyapps/certs/bb-sandbox/
    ##cp /root/ca/private/ca.key* /var/pyapps/certs/bb-sandbox/
    #chown -Rf pyapps:apache /var/pyapps/certs
    #ls -la /var/pyapps/certs/bb-sandbox
