---
# File: playbook/appserver/install_cert.yml
# Created: 5/31/17
# Author: '@ekivemark'

# install a private key to the appserver

# Based on: http://odecee.com.au/cloudformation-and-ansible/
# Vars file is relative to playbook file
# vars_files:
# Vars file is relative to playbook file
# Sequence:
# 1. Common variables
# 2. encrypted vault file
# 3. environment specific variables
# 4. all_vars which reference the preceding three files.
# common_ prefixes common variables
# vault_env_ prefixes encrypted variables
# env_ prefixes environment specific variables
# all_var incorporates preceding variables and defines variables without prefixes.
# use all_var variables in scripts.

- name: "Install Back-end client certificate"
  # hosts: appservers
  hosts: "{{ build_target }}"
  # connection: local
  remote_user: ec2-user
  # become_user: root
  # become: yes
  gather_facts: True
  vars:
    ansible_ssh_pipelining: no
    env: "dev"
    sub_zone: "app"
  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/env/{{ env }}/vault.yml"
    - "./../../vars/env/{{ env }}/env.yml"
    - "./../../vars/all_var.yml"

  roles:
    - include: roles/create_certstore

  tasks:
  - name: "Add certstore sub-folder"
    file: "{{ cf_app_pyapp_home }}/certstore/{{ cert_sub_dir }}"
    mode: 0755
    owner: "{{ cf_app_pyapps_user }}"
    group: "{{ app_group }}"
    recurse: yes
    state: directory



    # mkdir -p /var/pyapps/certs/bb-sandbox
    #cd /
    #unzip /home/ec2-user/download/certs.zip
    #cp /home/ec2-user/download/certs/* /var/pyapps/cets/bb-sandbox/
    #
    ##cp /root/ca/certs/ca.cert* /var/pyapps/certs/bb-sandbox/
    ##cp /root/ca/private/ca.key* /var/pyapps/certs/bb-sandbox/
    #chown -Rf pyapps:apache /var/pyapps/certs
    #ls -la /var/pyapps/certs/bb-sandbox
