---
# File: playbook/appserver/install_cert.yml
# Created: 5/31/17
# Author: '@ekivemark'

# install a private key to the appserver

# Based on: http://odecee.com.au/cloudformation-and-ansible/
# Vars file is relative to playbook file
# vars_files:
# Vars file is relative to playbook file
# Sequence:
# 1. Common variables
# 2. encrypted vault file
# 3. environment specific variables
# 4. all_vars which reference the preceding three files.
# common_ prefixes common variables
# vault_env_ prefixes encrypted variables
# env_ prefixes environment specific variables
# all_var incorporates preceding variables and defines variables without prefixes.
# use all_var variables in scripts.

- name: "Install Back-end client certificate"
  # hosts: appservers
  hosts: "{{ build_target }}"
  # connection: local
  remote_user: ec2-user
  become_user: root
  become: yes
  gather_facts: True
  vars:
    ansible_ssh_pipelining: no
    env: "dev"
    sub_zone: "app"
    # use extra-vars to define:

    # AppServer cert and key for communication with FHIR Server
    # app_fhir_cert: "{{ env_app_fhir_cert }}"
    # app_fhir_key: "{{ env_app_fhir_key }}"
    # app_fhir_cert_subdir: "{{ env_app_fhir_cert_subdir }}"
    # app_fhir_cert_name: "{{ env_app_fhir_cert_name }}"
    # app_fhir_key_name: "{{ env_app_fhir_key_name }}"



  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/env/{{ env }}/vault.yml"
    - "./../../vars/env/{{ env }}/env.yml"
    - "./../../vars/all_var.yml"



  tasks:
  - import_tasks: roles/create_certstore/tasks/main.yml

  - name: "Add {{ app_fhir_cert_subdir }} to certstore"
    file:
      dest: "{{ cf_app_pyapp_home }}/certstore/{{ app_fhir_cert_subdir }}"
      mode: 0755
      owner: "{{ cf_app_pyapps_user }}"
      group: "{{ app_group }}"
      recurse: yes
      state: directory

#  - name: "copy cert({{ src_cert }}) to certstore [{{ app_fhir_cert_subdir }}]"
#    copy:
#      src: "{{ src_cert_dir }}/{{ src_cert }}"
#      dest: "{{ cf_app_pyapp_home }}/certstore/{{ app_fhir_cert_subdir }}/{{ src_cert }}"
#      mode: 0755
#      owner: "{{ cf_app_pyapps_user }}"
#      group: "{{ app_group }}"
#    when: "src_cert_dir != '' and src_cert != '' "

  - name: "copy cert({{ app_fhir_cert_name }}) to certstore [{{ app_fhir_cert_subdir }}]"
    copy:
      content: "{{ app_fhir_cert }}"
      dest: "{{ cf_app_pyapp_home }}/certstore/{{ app_fhir_cert_subdir }}/{{ app_fhir_cert_name }}"
      mode: 0755
      owner: "{{ cf_app_pyapps_user }}"
      group: "{{ app_group }}"
    when: "app_fhir_cert_name != '' and app_fhir_cert != '' "


  - name: "copy key({{ app_fhir_key_name }}) to certstore [{{ app_fhir_cert_subdir }}]"
    copy:
      content: "{{ app_fhir_key }}"
      dest: "{{ cf_app_pyapp_home }}/certstore/{{ app_fhir_cert_subdir }}/{{ app_fhir_key_name }}"
      mode: 0755
      owner: "{{ cf_app_pyapps_user }}"
      group: "{{ app_group }}"
    when: "app_fhir_key_name != '' and app_fhir_key != '' "



    # mkdir -p /var/pyapps/certs/bb-sandbox
    #cd /
    #unzip /home/ec2-user/download/certs.zip
    #cp /home/ec2-user/download/certs/* /var/pyapps/certs/bb-sandbox/
    #
    ##cp /root/ca/certs/ca.cert* /var/pyapps/certs/bb-sandbox/
    ##cp /root/ca/private/ca.key* /var/pyapps/certs/bb-sandbox/
    #chown -Rf pyapps:apache /var/pyapps/certs
    #ls -la /var/pyapps/certs/bb-sandbox
