---
# File: playbook/appserver/refresh_server_code.yml
# Created: 6/1/17
# Author: '@ekivemark'

# Playbook to:
#  - refresh Django AppServer
#
# Based on: http://odecee.com.au/cloudformation-and-ansible/
# Vars file is relative to playbook file
# vars_files:
# Vars file is relative to playbook file
# Sequence:
# 1. Common variables
# 2. encrypted vault file
# 3. environment specific variables
# 4. all_vars which reference the preceding three files.
# common_ prefixes common variables
# vault_env_ prefixes encrypted variables
# env_ prefixes environment specific variables
# all_var incorporates preceding variables and defines variables without prefixes.
# use all_var variables in scripts.

- name: Refresh App Server
  # hosts: appservers
  hosts: "{{ build_target }}"
  # connection: local
  remote_user: ec2-user
  # become_user: root
  # become: yes
  gather_facts: True
  vars:
    ansible_ssh_pipelining: no
    # Choose update actions. Override with --extra-vars
    migrate: "yes"
    collectstatic: "yes"
    add_groups: "no"
    add_scopes: "no"
  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/env/{{ env }}/vault.yml"
    - "./../../vars/env/{{ env }}/env.yml"
    - "./../../vars/all_var.yml"

  roles:
    # - ../../roles/
    # - roles/
    # Check engine light
    - ../../roles/check_env
    # Update application code and write virtualhosts file
    - roles/app_update
    # Update environment variable files
    - roles/app_update_env
    # django migrate and collectstatic
    - roles/django_prep
    # Set permissions for app under selinux
    - roles/semanage_apps
    # Set permissions for virtualenv under selinux
    - roles/semanage_virtualenv


  tasks:
  - name: "restart apache"
    service:
      name: httpd
      state: restart


