---
# Playbook to update django app servers for the hhs_oauth_server environment
# # /etc/ansible/hosts defines the following servers:
# [loadbalancers]

# # Define one prime app server
# # This is used to perform the collectstatic command
# # to copy data to S3
# [appprimeserver]

# # If multiple availability zones are in use there will be a leader in each zone
# # but only one leader across all availability zones can be the prime
# [appleaderservers]

# # We currently configure one follower for each leader but there could be more
# [appfollowerservers]

# # Database Servers
# [dbservers]

# # Ansible Management Servers
# [mgmtservers]

# Apply only to prime app server
- hosts: appprimeserver
  # Vars file is relative to playbook folder
  vars_files:
    - ../../vars/playbook/vars.yml
  remote_user: "{{ remote_user_account }}"
  become: yes
  become_user: root
  
  tasks:
  - name: become root and activate virtualenv
    become: yes
    become_method: sudo
    become_user: root
    action: shell source /var/virtualenv/hhs_o_server/bin/activate

  - name: switch to app folder
    action: "shell cd {{ install_root }}/{{ project_name }}/"

  # - name: Django collectstatic
  - django_manage:
      command: collectstatic
      app_path: "{{ install_root }}/{{ project_name }}/"
      virtualenv: "{{ venv }}"

  - name: make sure apache server is running
    service: name=httpd state=started enabled=yes
 
  - name: Restart Apache
    action: shell /bin/echo $HOSTNAME
    notify:
      - restart apache
 
  handlers: 
    - name: restart apache
      service: name=httpd state=restarted  

# vim:ff=unix ts=2 sw=2 ai expandtab ft=ansible
