---
# File: playbook/appserver/test_ssl_off.yml
# Created: 5/25/17
# Author: '@ekivemark'

# test ssl_off role


- name: Test git deployments
  # hosts: appservers
  hosts: "{{ build_target }}"
  # connection: local
  remote_user: ec2-user
  # become_user: root
  # become: yes
  gather_facts: True

  roles:
    - ./roles/apache/tasks/ssl_off.yml

