---
# File: playbook/appserver/test_feature.yml
# Created: 5/16/17
# Author: '@ekivemark'

# Use this playbook to call roles and tasks for testing purposes only

- name: "Test Feature"
  # hosts: appservers
  # hosts: "{{ build_target }}"
  hosts: localhost
  # Disable if testing remote machine functions
  connection: local
  remote_user: ec2-user
  # become_user: root
  # become: yes
  gather_facts: True
  vars:
    ansible_ssh_pipelining: no
    env: "dev"
    azone: "az1"
    sub_zone: "app"
    sg_zone: "appserver"
    env_az: "{{ env }}-{{ azone }}"
    env_cf_app_version: "01"
    splunk_client_name: "BBAPI-{{ env|upper }}-{{ sub_zone|upper }}"
  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/env/{{ env }}/vault.yml"
    - "./../../vars/env/{{ env }}/env.yml"
    - "./../../vars/all_var.yml"

  tasks:
#  - name: "Show the ini file"
#    connection: local
#    shell: "cat /etc/ansible/hosts"
#    register: ansible_hosts_content
#
#  - debug:
#      msg: "{{ ansible_hosts_content }}"
#
#  - name: "add {{ build_target }} to appservers section"
#    connection: local
#    lineinfile:
#      dest: "/etc/ansible/hosts"
#      regexp: '\[appservers\]'
#      line: "[appservers]\n{{ build_target }}\n"
#
#  - name: "remove buildapp entry"
#    connection: local
#    blockinfile:
#      dest: "/etc/ansible/hosts"
#      marker: "# {mark} ANSIBLE MANAGED BLOCK buildapp #"
#      content: ""
#
#  - name: "Show the ini file"
#    connection: local
#    shell: "cat /etc/ansible/hosts"
#    register: ansible_hosts_content
#
#  - debug:
#      msg: "{{ ansible_hosts_content }}"
#
#  - name: "Get the database server"
#    debug:
#      msg: "the server ip address is {{ hostvars[groups['dbservers'][0]]['inventory_hostname'] }}"
  - name: get aws_region
    set_fact:
        aws_region: "{{ lookup('ini', 'region section=default file=/root/.aws/config') }}"
  - debug:
      msg: "using default region {{ aws_region }} "

  - name: get aws_key
    set_fact:
        aws_access_id: "{{ lookup('ini', 'aws_access_key_id section=default file=/root/.aws/credentials') }}"
  - debug:
      msg: "using default access key {{ aws_access_id }} "

  - name: get aws_secret
    set_fact:
        aws_secret_key_id: "{{ lookup('ini', 'aws_secret_access_key section=default file=/root/.aws/credentials') }}"
  - debug:
      msg: "using default secret {{ aws_secret_key_id }} "

  - name: "Get facts"
    become_user: root
    become: yes
    ec2_facts:
    register: ec2_facts_info
#
#  - name: show facts
#    debug:
#      msg: "{{ ec2_facts_info }}"
#
#  - name: get the instance_id
#    debug:
#      msg: "{{ ec2_facts_info['ansible_facts']['ansible_ec2_local_ipv4'] }} instance id is {{ ec2_facts_info['ansible_facts']['ansible_ec2_instance_id']}}"
#
#
  - name: "Get remote facts for vpc {{ cf_vpc_id }}"
    ec2_remote_facts:
      aws_access_key: "{{ aws_access_id }}"
      aws_secret_key: "{{ aws_secret_key_id }}"
      region: "{{ aws_region }}"
      filters:
        vpc_id: "{{ cf_vpc_id }}"
        Environment: "{{ env|upper }}"
        Managed: "BB-MANAGED-{{ env|upper }}"
    register: ec2_remote_facts_info

  - name: show facts
    debug:
      msg: "{{ ec2_remote_facts_info }}"

#
#  - name: "Get elb facts"
#    connection: local
#    action:
#      module: ec2_elb_facts
#      aws_access_key: "{{ aws_access_id }}"
#      aws_secret_key: "{{ aws_secret_key_id }}"
#      names: ['BB-DEV-WebLB-1-592302630.us-east-1.elb.amazonaws.com', 'BB-TEST-WEBLB-241569787.us-east-1.elb.amazonaws.com', 'BB-IMPL-WEBLB-2133808602.us-east-1.elb.amazonaws.com']
#      region: "{{ aws_region }}"
#    register: elb_facts
#
#  - name: "show elb facts"
#    debug:
#      msg: "{{ elb_facts }}"
#
#  - name: " Attach server to ec2_elb"
#    vars:
#      instance_to_attach: "{{ ec2_facts_info['ansible_facts']['ansible_ec2_instance_id']}}"
#    include: roles/attach_to_elb/tasks/main.yml
#

  - name: "write hosts file"
    connection: local
    template:
      src: ../../templates/environment/ansible_hosts.j2
      dest: /root/test_ansible_host


