---
# File: playbook/appserver/test_feature.yml
# Created: 5/16/17
# Author: '@ekivemark'

# Use this playbook to call roles and tasks for testing purposes only

- name: "Test Feature"
  # hosts: appservers
  hosts: "{{ build_target }}"
  # connection: local
  remote_user: ec2-user
  # become_user: root
  # become: yes
  gather_facts: True
  vars:
    ansible_ssh_pipelining: no
    env: "dev"
    azone: "az1"
    sub_zone: "app"
    sg_zone: "appserver"
    env_az: "{{ env }}-{{ azone }}"
    env_cf_app_version: "01"
    splunk_client_name: "BBAPI-{{ env|upper }}-{{ sub_zone|upper }}"
  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/env/{{ env }}/vault.yml"
    - "./../../vars/env/{{ env }}/env.yml"
    - "./../../vars/all_var.yml"

  tasks:
  - name: "Get the database server"
    debug:
      msg: "the server ip address is {{ hostvars }}"
