---
# File: playbook/appserver/test_feature.yml
# Created: 5/16/17
# Author: '@ekivemark'

# Use this playbook to call roles and tasks for testing purposes only

- name: "Test Feature"
  # hosts: appservers
  hosts: localhost  ## "{{ build_target }}"
  # Disable if testing remote machine functions
  connection: local
  remote_user: ec2-user
  # become_user: root
  # become: yes
  gather_facts: True
  vars:
    ansible_ssh_pipelining: no
    env: "dev"
    azone: "az1"
    sub_zone: "app"
    sg_zone: "appserver"
    env_az: "{{ env }}-{{ azone }}"
    env_cf_app_version: "01"
    splunk_client_name: "BBAPI-{{ env|upper }}-{{ sub_zone|upper }}"
  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/env/{{ env }}/vault.yml"
    - "./../../vars/env/{{ env }}/env.yml"
    - "./../../vars/all_var.yml"

  tasks:
#  - name: "Get the database server"
#    debug:
#      msg: "the server ip address is {{ hostvars[groups['dbservers'][0]]['inventory_hostname'] }}"
  - name: get aws_region
    set_fact:
        aws_region: "{{ lookup('ini', 'region section=default file=/root/.aws/config') }}"
  - debug:
      msg: "using default region {{ aws_region }} "


  - name: get aws_key
    set_fact:
        aws_access_id: "{{ lookup('ini', 'aws_access_key_id section=default file=/root/.aws/credentials') }}"
  - debug:
      msg: "using default access key {{ aws_access_id }} "

  - name: get aws_secret
    set_fact:
        aws_secret_key_id: "{{ lookup('ini', 'aws_secret_access_key section=default file=/root/.aws/credentials') }}"
  - debug:
      msg: "using default secret {{ aws_secret_key_id }} "

  - name: "Get facts"
    ec2_facts:
    register: ec2_facts_info

  - name: show facts
    debug:
      msg: "{{ ec2_facts_info }}"

  - name: "Get remote facts for vpc {{ cf_vpc_id }}"
    ec2_remote_facts:
      aws_access_key: "{{ aws_access_id }}"
      aws_secret_key: "{{ aws_secret_key_id }}"
      region: "{{ aws_region }}"
      filters:
        vpc_id: "{{ cf_vpc_id }}"
    register: ec2_remote_facts_info

  - name: show facts
    debug:
      msg: "{{ ec2_remote_facts_info }}"


#  - name: " Attach server to ec2_elb"
#    include: roles/attach_to_elb/tasks/main.yml

