---
# File: playbook/appserver/update_appserver.yml
# Created: 5/24/17
# Author: '@ekivemark'

# Playbook to:
#  - Update Python3/Django AppServer
#
# Based on: http://odecee.com.au/cloudformation-and-ansible/
# Vars file is relative to playbook file
# vars_files:
# Vars file is relative to playbook file
# Sequence:
# 1. Common variables
# 2. encrypted vault file
# 3. environment specific variables
# 4. all_vars which reference the preceding three files.
# common_ prefixes common variables
# vault_env_ prefixes encrypted variables
# env_ prefixes environment specific variables
# all_var incorporates preceding variables and defines variables without prefixes.
# use all_var variables in scripts.
# Implementing Nessus rewrite patch to virtualhosts.conf
# Switch off default ssl.conf (ssl is handled by front-end App Load Balancer)
# Release: Nessus Trace fix 2017-05-18

- name: Update AppServer
  # hosts: appservers
  hosts: "{{ build_target }}"
  # connection: local
  remote_user: ec2-user
  # become_user: root
  # become: yes
  gather_facts: True
  vars:
    ansible_ssh_pipelining: no
    env: "dev"
    azone: "az1"
    sub_zone: "app"
    sg_zone: "appserver"
    env_az: "{{ env }}-{{ azone }}"
    env_cf_app_version: "01"
    splunk_client_name: "BBAPI-{{ env|upper }}-{{ sub_zone|upper }}"
    migrate: "yes"
    collectstatic: "yes"
  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/env/{{ env }}/vault.yml"
    - "./../../vars/env/{{ env }}/env.yml"
    - "./../../vars/all_var.yml"

  tasks:
  - include: ../../roles/base_patch/tasks/update_packages.yml
    # Switch default ssl.conf off
  - include: roles/apache/tasks/ssl_off.yml
  - include: ./write_virtual_hosts.yml

  - name: make sure apache server is running
    service:
      name: httpd
      state: started
      enabled: yes

  - name: "Restart Apache on {{ env }}"
    action: shell /bin/echo $HOSTNAME
    notify:
      - restart apache

  handlers:
  - name: restart apache
    service: name=httpd state=restarted

