---
# File: playbook/mgmtserver/add_ansible_user.yml
# Created: 5/30/17
# Author: '@ekivemark'

- name: "Create Ansible Management Users"
  hosts: "{{ build_target }}"
  become_user: root
  remote_user: ec2-user
  become: yes
  connection: smart
  vars:
    # det a default environment. We don't mind mucking with the dev environment
    env: "dev"
    ansible_ssh_pipelining: no
  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/env/{{ env }}/vault.yml"
    - "./../../vars/env/{{ env }}/env.yml"
    - "./../../vars/all_var.yml"


  tasks:
  - name: Add group "ansmgmt"
    become_user: root
    become: yes
    group:
      name: ansmgmt
      state: present

  - include: roles/mgmt_user_add/tasks/main.yml
