---
# File: playbook/mgmtserver/Create_Certificates.yml
# Created: 6/16/17
# Author: '@ekivemark'

- name: "Create Certificate setup on MgmtServer"
  hosts: "{{ build_target }}"
  become_user: root
  remote_user: ec2-user
  become: yes
  connection: smart
  vars:
    # det a default environment. We don't mind mucking with the dev environment
    env: "dev"
    ansible_ssh_pipelining: no
    ans_group: "ansmgmt"
    ca_key: "server.key"
    ca_cert: "server.crt"

  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/env/{{ env }}/vault.yml"
    - "./../../vars/env/{{ env }}/env.yml"
    - "./../../vars/all_var.yml"
    # Load certificate values
    # ca_commonname is empty - this needs to be set to server name
    - "./../../vars/env/{{ env }}/ca_env.yml"


  tasks:
  - name: "Ensure openssl is installed"
    yum:
      name: openssl
      state: latest

  - name: "Delete ca-certs directory"
    file:
      path: "{{ item }}"
      state: absent
      owner: root
      group: root
    with_items:
    - "{{ ca_certs_dir }}"

  - name: "Make configuration directories"
    file:
      path: "{{ item }}"
      state: directory
      recurse: yes
      owner: root
      group: root
    with_items:
    - "{{ ca_certs_dir }}"
    - "{{ ca_certs_dir }}/certs"
    - "{{ ca_certs_dir }}/crl"
    - "{{ ca_certs_dir }}/newcerts"
    - "{{ ca_certs_dir }}/private"

  - name: "Deploy configuration items"
    template:
      src: "./../../templates/mgmtserver/{{ item }}.j2"
      dest: "{{ ca_certs_dir }}/{{ item }}"
      owner: root
      group: root
    with_items:
    - serial
    - ca.conf

  - name: "set CA_SUBJECT var"
    set_fact:
      ca_subject: '/C={{ ca_country }}/ST={{ ca_state }}/L={{ ca_locality }}/O={{ ca_organization }}/OU={{ ca_organizationalunit }}/CN={{ ca_commonname }}/emailAddress={{ ca_email }}'
    when: ca_subject is not defined


  # CA root ca password
  - name: "Generate private key and Create root CA files"
    shell: "{{ item }}"
    args:
      chdir: "{{ ca_certs_dir }}"
    with_items:
    - "openssl genrsa -out {{ ca_key }} 2048"
    - "openssl req -config {{ ca_certs_dir }}/ca.conf -new -key {{ ca_key }} -x509 -days 1825 -out {{ ca_cert }} -passin pass:{{ ca_rootca_password }} -subj \"{{ ca_subject }}\""

  - name: "Check certs"
    debug:
      msg: "check certs"