# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "bb2-terraform-state"
    encrypt = true
    key     = "test_V4/terraform.tfstate"
    region  = "us-east-1"
  }
}
