# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "bb2-terraform-state"
    #dynamodb_table = "bb-terraform-state"
    encrypt        = true
    key            = "test/terraform.tfstate"
    region         = "us-east-1"
  }
}
