---
# File: playbook/mgmtserver/roles/letsencrypt_mgmt_certstore/tasks/main.yml
# Created: 6/26/17
# Author: '@ekivemark'
# create certstore directory

- name: "setup local /root/CERTSTORE"
  file:
    dest: "/root/certstore/{{ env }}/"
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: "0600"

