---
# File: playbook/appserver/roles/attach_to_elb/tasks/main.yml
# Created: 5/16/17
# Author: '@ekivemark'
# Attach server to ELB

- name: "get instance_id"
  debug:
    msg: "Instance is {{ instance_to_attach }}"

- name: "get elbs"
  debug:
    msg: "the elbs are - {{ elb_facts }}"

# elbv2 command requires newer version of awscli (1.11)
# pip install --upgrade --user awscli
# installed as: /root/.local/bin/aws
# aws-cli/1.11.86 Python/2.7.5 Linux/3.10.0-514.10.2.el7.x86_64 botocore/1.5.49
# Server comes with v 1.10 in /usr/local/bin/aws
# aws-cli/1.10.7 Python/2.7.5 Linux/3.10.0-514.10.2.el7.x86_64 botocore/1.3.29
- name: "attach server to Application LB"
  connection: local
  shell: "/root/.local/bin/aws elbv2 register-targets --target-group-arn {{ app_lb_arn }} --targets Id={{ instance_to_attach }} "
  register: app_lb_result

