---
# File: playbook/appserver/roles/attach_to_elb/tasks/main.yml
# Created: 5/16/17
# Author: '@ekivemark'
# Attach server to ELB

- name: "get instance_id"
  debug:
    msg: "Instance is {{ instance_to_attach }}"

- name: "get elbs"
  debug:
    msg: "the elbs are - {{ elb_facts }}"

- name: "attach server to Application LB"
  local_action:
    shell: "aws elbv2 register-targets --target-group-arn {{ app_lb_arn }} --targets Id={{ instance_to_attach }} "
  register: app_lb_result

