---
# File: main 
# Created: 5/4/17
# Author: @ekivemark

- name: "Create FIPS140 directory"
  file:
    path: /root/fips140
    state: directory
    owner: root
    group: root

- name: "install FIPS 140 script..."
  copy:
    mode: "u+x"
    owner: root
    group: root
    src: "{{ role_path }}/files/fips_update.sh"
    dest: "/root/fips140/fips_update.sh"

# yum update run in base_patch
# install fips modules
- name: "FIPS 140.2 install step 2"
  yum: pkg={{item}} state=installed
  with_items:
   - dracut-fips
   - dracut-fips-aesni

- name: "Backup initramfs"
  become_user: root
  shell: "mv -v /boot/initramfs-$(uname -r).img{,.bak} >> $LOG_FILE 2>&1"

- name: "run dracut to rebuild initramfs"
  become_user: root
  shell: "dracut -f "

- name: "Rebooting after step 1/4 ..."
  command: shutdown -r now "Reboot required after FIPS Step 1 install"
  # async: 0
  # poll: 0
  become_user: root
  ignore_errors: true
  when: reboot_hint.stdout.find("reboot") != -1
  register: rebooting_1

- name: "Wait for thing to reboot..."
  pause: seconds=45
  when: rebooting_1|changed


- name: "FIPS setup step 2/4..."
  become_user: root
  shell: "/root/fips140/fips_update.sh 2"

- name: "Rebooting after step 2/4 ..."
  command: shutdown -r now "Reboot required after FIPS Step 2 install"
  async: 0
  poll: 0
  become_user: root
  ignore_errors: true
  when: reboot_hint.stdout.find("reboot") != -1
  register: rebooting_2

- name: "Wait for thing to reboot..."
  pause: seconds=45
  when: rebooting_2|changed

- name: "FIPS setup step 3/4..."
  become_user: root
  shell: "/root/fips140/fips_update.sh 3"

- name: "Rebooting after step 3/4 ..."
  command: shutdown -r now "Reboot required after FIPS Step 3 install"
  async: 0
  poll: 0
  become_user: root
  ignore_errors: true
  when: reboot_hint.stdout.find("reboot") != -1
  register: rebooting_3

- name: "Wait for thing to reboot..."
  pause: seconds=45
  when: rebooting_3|changed

- name: "FIPS setup step 4/4..."
  become_user: root
  shell: "/root/fips140/fips_update.sh 4"
  register: rebooting_4



