---
# File: main 
# Created: 5/4/17
# Author: @ekivemark

- name: "configure rhn for postgresql"
  become_user: root
  shell: "echo 'exclude=postgresql*' >>/etc/yum/pluginconf.d/rhnplugin.conf"

- name: "Install Postgresql components"
  yum:
    pkg: "{{item}}"
    state: installed
  with_items:
   - https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-6-x86_64/pgdg-redhat96-9.6-3.noarch.rpm
   - postgresql96-server
   - https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-6-x86_64/postgresql96-contrib-9.6.1-1PGDG.rhel6.x86_64.rpm

- name: "Define PGDATA Location"

