---
# File: main 
# Created: 5/4/17
# Author: @ekivemark

- name: "Create FIPS140 directory"
  file:
    path: /root/fips140
    state: directory
    owner: root
    group: root

- name: "install FIPS 140 script..."
  copy:
    mode: "u+x"
    owner: root
    group: root
    src: "{{ role_path }}/files/fips_update.sh"
    dest: "/root/fips140/fips_update.sh"

- name: "FIPS setup step 1/4..."
  become_user: root
  shell: "/root/fips140/fips_update.sh 1"
  register: rebooting_1
  notify:
   - Wait for server to restart

- name: "FIPS setup step 2/4..."
  become_user: root
  shell: "/root/fips140/fips_update.sh 2"
  register: rebooting_2
  notify:
   - Wait for server to restart

- name: "FIPS setup step 3/4..."
  become_user: root
  shell: "/root/fips140/fips_update.sh 3"
  register: rebooting_3
  notify:
   - Wait for server to restart

- name: "FIPS setup step 4/4..."
  become_user: root
  shell: "/root/fips140/fips_update.sh 3"
  register: rebooting_4




