---
# File: pgpass.yml 
# Created: 5/7/17
# Author: '@ekivemark'

- name: "Create .pgpass file"
  template:
    src: "../templates/pgpass.j2"
    dest: "{{ db_server_data_dir }}/.pgpass"
    owner: "{{ db_server_account }}"
    group: "{{ db_server_account }}"
    mode: "0600"
