---
# File: roles/python34/tasks/main.yml
# Created: 5/10/17
# Author: '@ekivemark'
# download and install python3
# Check for python version

- name: "Install Python 3.4"
  become_user: root
  become: yes
  yum:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - python34


