---
# File: playbook/appherd/roles/app_prep/tasks/main.yml
# Created: 11/27/17
# last modified: 11/27/17
# Author: '@ekivemark'
# prepare the application environment folders

- name: " Create the virtualenv folder"
  become_user: root
  become: yes
  file:
    dest: "/var/virtualenv"
    owner: "{{ cf_app_pyapps_user }}"
    group: "{{ cf_app_pyapps_user }}"
    mode: 0755
    state: directory

- name: "Create the app folder"
  become_user: root
  become: yes
  file:
    dest: "/var/pyapps"
    owner: "{{ cf_app_pyapps_user }}"
    group: "{{ cf_app_pyapps_user }}"
    mode: 0755
    state: directory

- name: "Create the app log directory "
  become_user: root
  become: yes
  file:
    dest: "{{ cf_app_log_dir }}"
    owner: "{{ cf_app_pyapps_user }}"
    group: "logreader"
    state: directory
    mode: 0755

- name: "Create the log files"
  become_user: root
  become: yes
  file:
    dest: "{{ cf_app_log_dir }}/{{ item }}"
    owner: "{{ cf_app_pyapps_user }}"
    group: "logreader"
    state: touch
    mode: 0766
  with_items:
    - debug.log
    - error.log
    - info.log
    - login_failed.log
    - admin_access.log
    - perf_mon.log
