apiVersion: v1
kind: Pod
spec:
  containers:
    - name: bb2-cbc-build
      image: "public.ecr.aws/f5g8o1y9/bb2-cbc-build:py3810-an2922-tf12-boto3-botocore-jinja2"
      tty: true
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
  nodeSelector:
    Agents: true
