apiVersion: v1
kind: Pod
spec:
  containers:
    - name: bb2-cbc-build
      image: "public.ecr.aws/f5g8o1y9/bb2-cbc-build:py311-ans11-awscol620-tf18-tgrunt-boto3-botocore-packer11-V2"
      tty: true
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
  nodeSelector:
      Agents: true