apiVersion: v1
kind: Pod
spec:
  containers:
    - name: bb2-cbc-build
      image: "public.ecr.aws/f5g8o1y9/bb2-cbc-build:py38-ans29-awscol620-tf12-tgrunt-boto3-botocore"
      tty: true
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
  nodeSelector:
      Agents: true