apiVersion: v1
kind: Pod
spec:
  containers:
    - name: bb2-cbc-build
      image: "public.ecr.aws/q8j7a4l4/bb2-cbc-build:py311-ans11-awscol620-ot10-tgrunt85-boto3-botocore-V3"
      tty: true
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
  nodeSelector:
      Agents: true