---
- name: "Write custom-envvars file"
  become_user: "{{ remote_admin_account }}"
  become: yes
  template:
    src: ../templates/custom-envvars.j2
    dest: "{{ install_root }}/custom-envvars.py"
    backup: yes
    owner: "{{ app_owner }}"
    group: "{{ app_group }}"
    mode: 0664

- name: "Write django_settings.sh script"
  become_user: "{{ remote_admin_account }}"
  become: yes
  template:
    src: ../templates/django_settings.j2
    dest: "{{ install_root }}/django_settings.sh"
    backup: yes
    owner: "{{ app_owner }}"
    group: "{{ app_group }}"
    mode: 0664

- name: "Make new files executable"
  become_user: "{{ remote_admin_account }}"
  become: yes
  shell: "chmod +x {{ cf_app_pyapp_home }}"
